export const ACHIEVEMENTS = [
  { id: 'kills_1', name: 'Primeiro Abate', description: 'Elimine seu primeiro inimigo.', rarity: 'COMMON', type: 'cumulative', stat: 'kills', target: 1 },
  { id: 'kills_5', name: 'Iniciante', description: 'Elimine 5 inimigos.', rarity: 'COMMON', type: 'cumulative', stat: 'kills', target: 5 },
  { id: 'kills_10', name: 'Dez Vidas', description: 'Elimine 10 inimigos.', rarity: 'COMMON', type: 'cumulative', stat: 'kills', target: 10 },
  { id: 'kills_25', name: 'Atirador', description: 'Elimine 25 inimigos.', rarity: 'COMMON', type: 'cumulative', stat: 'kills', target: 25 },
  { id: 'money_500', name: 'Trocados', description: 'Acumule R$500 em uma partida.', rarity: 'COMMON', type: 'cumulative', stat: 'moneyEarned', target: 500 },
  { id: 'money_1000', name: 'Mil Reais', description: 'Acumule R$1.000 em uma partida.', rarity: 'COMMON', type: 'cumulative', stat: 'moneyEarned', target: 1000 },
  { id: 'tokens_1', name: 'Primeiro Token', description: 'Ganhe seu primeiro token.', rarity: 'COMMON', type: 'cumulative', stat: 'tokensEarned', target: 1 },
  { id: 'wave_3', name: 'Tres Ondas', description: 'Sobreviva ate a Wave 3.', rarity: 'COMMON', type: 'cumulative', stat: 'waves', target: 3 },
  { id: 'wave_5', name: 'Cinco Ondas', description: 'Sobreviva ate a Wave 5.', rarity: 'COMMON', type: 'cumulative', stat: 'waves', target: 5 },
  { id: 'level_3', name: 'Nivel 3', description: 'Alcance o nivel 3.', rarity: 'COMMON', type: 'cumulative', stat: 'level', target: 3 },
  { id: 'level_5', name: 'Nivel 5', description: 'Alcance o nivel 5.', rarity: 'COMMON', type: 'cumulative', stat: 'level', target: 5 },
  { id: 'weapons_1', name: 'Armado', description: 'Possua pelo menos 1 arma.', rarity: 'COMMON', type: 'instant', test: g => g.weapon.inventory.length >= 1 },
  { id: 'weapons_2', name: 'Duas Armas', description: 'Possua 2 armas diferentes.', rarity: 'COMMON', type: 'cumulative', stat: 'weaponsOwned', target: 2 },
  { id: 'miniboss_1', name: 'Mini Chefe', description: 'Derrote seu primeiro mini-boss.', rarity: 'COMMON', type: 'cumulative', stat: 'minibosses', target: 1 },
  { id: 'dmg_1000', name: 'Mil de Dano', description: 'Cause 1.000 de dano total.', rarity: 'COMMON', type: 'cumulative', stat: 'damageDealt', target: 1000 },
  { id: 'dmg_5000', name: 'Cinco Mil de Dano', description: 'Cause 5.000 de dano total.', rarity: 'COMMON', type: 'cumulative', stat: 'damageDealt', target: 5000 },
  { id: 'first_revive', name: 'Renascido', description: 'Use um revive pela primeira vez.', rarity: 'COMMON', type: 'cumulative', stat: 'revivesUsed', target: 1 },
  { id: 'armor_1', name: 'Primeira Armadura', description: 'Adquira sua primeira armadura.', rarity: 'COMMON', type: 'cumulative', stat: 'armorsOwned', target: 1 },
  { id: 'play_1', name: 'Primeira Partida', description: 'Complete sua primeira partida.', rarity: 'COMMON', type: 'cumulative', stat: 'matchesPlayed', target: 1 },
  { id: 'death_1', name: 'Primeira Morte', description: 'Morra pela primeira vez.', rarity: 'COMMON', type: 'cumulative', stat: 'deaths', target: 1 },
  { id: 'collect_5', name: 'Colecionador', description: 'Colete 5 drops no chao.', rarity: 'COMMON', type: 'cumulative', stat: 'dropsCollected', target: 5 },
  { id: 'boss_1', name: 'Primeiro Chefe', description: 'Derrote seu primeiro boss.', rarity: 'COMMON', type: 'cumulative', stat: 'bosses', target: 1 },
  { id: 'wave_7', name: 'Sete Ondas', description: 'Sobreviva ate a Wave 7.', rarity: 'COMMON', type: 'cumulative', stat: 'waves', target: 7 },
  { id: 'money_2500', name: 'Poupanca', description: 'Acumule R$2.500 em uma partida.', rarity: 'COMMON', type: 'cumulative', stat: 'moneyEarned', target: 2500 },
  { id: 'tokens_5', name: 'Cinco Tokens', description: 'Acumule 5 tokens.', rarity: 'COMMON', type: 'cumulative', stat: 'tokensEarned', target: 5 },
  { id: 'kill_streak_3', name: 'Sequencia de 3', description: 'Mate 3 inimigos seguidos sem morrer.', rarity: 'COMMON', type: 'instant', test: g => (g.stats.killStreak || 0) >= 3 },
  { id: 'level_8', name: 'Nivel 8', description: 'Alcance o nivel 8.', rarity: 'COMMON', type: 'cumulative', stat: 'level', target: 8 },
  { id: 'dmg_10000', name: 'Dez Mil de Dano', description: 'Cause 10.000 de dano total.', rarity: 'COMMON', type: 'cumulative', stat: 'damageDealt', target: 10000 },
  { id: 'wave_10', name: 'Dez Ondas', description: 'Sobreviva ate a Wave 10.', rarity: 'COMMON', type: 'cumulative', stat: 'waves', target: 10 },
  { id: 'melee_50', name: 'Corpo a Corpo', description: 'Elimine 50 inimigos com armas corpo a corpo.', rarity: 'COMMON', type: 'cumulative', stat: 'meleeKills', target: 50 },

  { id: 'kills_50', name: 'Cacador', description: 'Elimine 50 inimigos.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'kills', target: 50 },
  { id: 'kills_75', name: 'Matador', description: 'Elimine 75 inimigos.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'kills', target: 75 },
  { id: 'kills_100', name: 'Centuria', description: 'Elimine 100 inimigos.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'kills', target: 100 },
  { id: 'money_5000', name: 'Rico', description: 'Acumule R$5.000 em uma partida.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'moneyEarned', target: 5000 },
  { id: 'money_10000', name: 'Investidor', description: 'Acumule R$10.000 em uma partida.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'moneyEarned', target: 10000 },
  { id: 'tokens_10', name: 'Dez Tokens', description: 'Acumule 10 tokens.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'tokensEarned', target: 10 },
  { id: 'tokens_25', name: 'Token Collector', description: 'Acumule 25 tokens.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'tokensEarned', target: 25 },
  { id: 'wave_15', name: 'Quinze Ondas', description: 'Sobreviva ate a Wave 15.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'waves', target: 15 },
  { id: 'wave_20', name: 'Vinte Ondas', description: 'Sobreviva ate a Wave 20.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'waves', target: 20 },
  { id: 'level_15', name: 'Nivel 15', description: 'Alcance o nivel 15.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'level', target: 15 },
  { id: 'level_20', name: 'Nivel 20', description: 'Alcance o nivel 20.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'level', target: 20 },
  { id: 'level_25', name: 'Nivel 25', description: 'Alcance o nivel 25.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'level', target: 25 },
  { id: 'weapons_4', name: 'Arsenal', description: 'Possua 4 armas diferentes.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'weaponsOwned', target: 4 },
  { id: 'weapons_5', name: 'Cinco Armas', description: 'Possua 5 armas diferentes.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'weaponsOwned', target: 5 },
  { id: 'boss_5', name: 'Cinco Chefes', description: 'Derrote 5 chefes.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'bosses', target: 5 },
  { id: 'miniboss_5', name: 'Cinco Minis', description: 'Derrote 5 mini-bosses.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'minibosses', target: 5 },
  { id: 'miniboss_10', name: 'Dez Minis', description: 'Derrote 10 mini-bosses.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'minibosses', target: 10 },
  { id: 'armors_2', name: 'Duas Armaduras', description: 'Adquira 2 armaduras diferentes.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'armorsOwned', target: 2 },
  { id: 'armors_3', name: 'Tres Armaduras', description: 'Adquira 3 armaduras diferentes.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'armorsOwned', target: 3 },
  { id: 'dmg_50000', name: 'Cinquenta Mil de Dano', description: 'Cause 50.000 de dano total.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'damageDealt', target: 50000 },
  { id: 'dmg_100000', name: 'Cem Mil de Dano', description: 'Cause 100.000 de dano total.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'damageDealt', target: 100000 },
  { id: 'revive_3', name: 'Gato de Sete Vidas', description: 'Use 3 revives.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'revivesUsed', target: 3 },
  { id: 'collect_25', name: 'Recolecionador', description: 'Colete 25 drops no chao.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'dropsCollected', target: 25 },
  { id: 'kill_streak_5', name: 'Sequencia de 5', description: 'Mate 5 inimigos seguidos sem morrer.', rarity: 'UNCOMMON', type: 'instant', test: g => (g.stats.killStreak || 0) >= 5 },
  { id: 'play_5', name: 'Jogador Assiduo', description: 'Complete 5 partidas.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'matchesPlayed', target: 5 },
  { id: 'match_win_3', name: 'Tres Vitorias', description: 'Venca 3 partidas.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'matchesWon', target: 3 },
  { id: 'time_300', name: 'Sobrevivente', description: 'Sobreviva por 5 minutos em uma partida.', rarity: 'UNCOMMON', type: 'instant', test: g => (g.stats.survivalTime || 0) >= 300 },
  { id: 'headshot_10', name: 'Atirador de Cabeca', description: 'Acerte 10 headshots.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'headshots', target: 10 },
  { id: 'speed_100', name: 'Veloz', description: 'Alcance 100 de velocidade acumulada.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'speedBoostsUsed', target: 10 },
  { id: 'wave_12', name: 'Ondas Intermediarias', description: 'Sobreviva ate a Wave 12.', rarity: 'UNCOMMON', type: 'cumulative', stat: 'waves', target: 12 },

  { id: 'kills_150', name: 'Predador', description: 'Elimine 150 inimigos.', rarity: 'RARE', type: 'cumulative', stat: 'kills', target: 150 },
  { id: 'kills_200', name: 'Falcao', description: 'Elimine 200 inimigos.', rarity: 'RARE', type: 'cumulative', stat: 'kills', target: 200 },
  { id: 'kills_250', name: 'Exterminador', description: 'Elimine 250 inimigos.', rarity: 'RARE', type: 'cumulative', stat: 'kills', target: 250 },
  { id: 'kills_300', name: 'Devorador', description: 'Elimine 300 inimigos.', rarity: 'RARE', type: 'cumulative', stat: 'kills', target: 300 },
  { id: 'money_25000', name: 'Barao', description: 'Acumule R$25.000 em uma partida.', rarity: 'RARE', type: 'cumulative', stat: 'moneyEarned', target: 25000 },
  { id: 'money_50000', name: 'Magnata', description: 'Acumule R$50.000 em uma partida.', rarity: 'RARE', type: 'cumulative', stat: 'moneyEarned', target: 50000 },
  { id: 'tokens_50', name: 'Token Collector', description: 'Acumule 50 tokens.', rarity: 'RARE', type: 'cumulative', stat: 'tokensEarned', target: 50 },
  { id: 'tokens_75', name: 'Token Expert', description: 'Acumule 75 tokens.', rarity: 'RARE', type: 'cumulative', stat: 'tokensEarned', target: 75 },
  { id: 'wave_25', name: 'Vinte e Cinco Ondas', description: 'Sobreviva ate a Wave 25.', rarity: 'RARE', type: 'cumulative', stat: 'waves', target: 25 },
  { id: 'wave_30', name: 'Trinta Ondas', description: 'Sobreviva ate a Wave 30.', rarity: 'RARE', type: 'cumulative', stat: 'waves', target: 30 },
  { id: 'level_30', name: 'Nivel 30', description: 'Alcance o nivel 30.', rarity: 'RARE', type: 'cumulative', stat: 'level', target: 30 },
  { id: 'level_40', name: 'Nivel 40', description: 'Alcance o nivel 40.', rarity: 'RARE', type: 'cumulative', stat: 'level', target: 40 },
  { id: 'level_50', name: 'Nivel 50', description: 'Alcance o nivel 50.', rarity: 'RARE', type: 'cumulative', stat: 'level', target: 50 },
  { id: 'weapons_7', name: 'Todas as Armas', description: 'Possua todas as 7 armas basicas.', rarity: 'RARE', type: 'cumulative', stat: 'weaponsOwned', target: 7 },
  { id: 'boss_10', name: 'Dez Chefes', description: 'Derrote 10 chefes.', rarity: 'RARE', type: 'cumulative', stat: 'bosses', target: 10 },
  { id: 'miniboss_25', name: 'Vinte e Cinco Minis', description: 'Derrote 25 mini-bosses.', rarity: 'RARE', type: 'cumulative', stat: 'minibosses', target: 25 },
  { id: 'armors_4', name: 'Quatro Armaduras', description: 'Adquira 4 armaduras diferentes.', rarity: 'RARE', type: 'cumulative', stat: 'armorsOwned', target: 4 },
  { id: 'armors_5', name: 'Cinto de Ferro', description: 'Adquira 5 armaduras diferentes.', rarity: 'RARE', type: 'cumulative', stat: 'armorsOwned', target: 5 },
  { id: 'dmg_500000', name: 'Meio Milhao de Dano', description: 'Cause 500.000 de dano total.', rarity: 'RARE', type: 'cumulative', stat: 'damageDealt', target: 500000 },
  { id: 'revive_5', name: 'Imortal', description: 'Use 5 revives.', rarity: 'RARE', type: 'cumulative', stat: 'revivesUsed', target: 5 },
  { id: 'kill_streak_10', name: 'Sequencia de 10', description: 'Mate 10 inimigos seguidos sem morrer.', rarity: 'RARE', type: 'instant', test: g => (g.stats.killStreak || 0) >= 10 },
  { id: 'play_15', name: 'Veterano', description: 'Complete 15 partidas.', rarity: 'RARE', type: 'cumulative', stat: 'matchesPlayed', target: 15 },
  { id: 'match_win_10', name: 'Dez Vitorias', description: 'Venca 10 partidas.', rarity: 'RARE', type: 'cumulative', stat: 'matchesWon', target: 10 },
  { id: 'headshot_50', name: 'Sniper Natural', description: 'Acerte 50 headshots.', rarity: 'RARE', type: 'cumulative', stat: 'headshots', target: 50 },
  { id: 'boss_10_dmg', name: 'Esmague o Chefe', description: 'Cause 10.000 de dano em um unico boss.', rarity: 'RARE', type: 'instant', test: g => (g.stats.maxBossDamage || 0) >= 10000 },
  { id: 'no_damage_wave', name: 'Perfeito', description: 'Complete uma wave sem levar dano.', rarity: 'RARE', type: 'instant', test: g => (g.stats.perfectWaves || 0) >= 1 },
  { id: 'wave_35', name: 'Trinta e Cinco Ondas', description: 'Sobreviva ate a Wave 35.', rarity: 'RARE', type: 'cumulative', stat: 'waves', target: 35 },
  { id: 'collect_100', name: 'Grande Colecionador', description: 'Colete 100 drops no chao.', rarity: 'RARE', type: 'cumulative', stat: 'dropsCollected', target: 100 },
  { id: 'miniboss_15', name: 'Quinze Minis', description: 'Derrote 15 mini-bosses.', rarity: 'RARE', type: 'cumulative', stat: 'minibosses', target: 15 },

  { id: 'kills_400', name: 'Carnical', description: 'Elimine 400 inimigos.', rarity: 'EPIC', type: 'cumulative', stat: 'kills', target: 400 },
  { id: 'kills_500', name: 'Lenda Viva', description: 'Elimine 500 inimigos.', rarity: 'EPIC', type: 'cumulative', stat: 'kills', target: 500 },
  { id: 'kills_750', name: 'Abatedor', description: 'Elimine 750 inimigos.', rarity: 'EPIC', type: 'cumulative', stat: 'kills', target: 750 },
  { id: 'money_100000', name: 'Milionario', description: 'Acumule R$100.000 em uma partida.', rarity: 'EPIC', type: 'cumulative', stat: 'moneyEarned', target: 100000 },
  { id: 'money_250000', name: 'Duvidoso', description: 'Acumule R$250.000 em uma partida.', rarity: 'EPIC', type: 'cumulative', stat: 'moneyEarned', target: 250000 },
  { id: 'tokens_100', name: 'Cem Tokens', description: 'Acumule 100 tokens.', rarity: 'EPIC', type: 'cumulative', stat: 'tokensEarned', target: 100 },
  { id: 'tokens_150', name: 'Token Lord', description: 'Acumule 150 tokens.', rarity: 'EPIC', type: 'cumulative', stat: 'tokensEarned', target: 150 },
  { id: 'wave_40', name: 'Quarenta Ondas', description: 'Sobreviva ate a Wave 40.', rarity: 'EPIC', type: 'cumulative', stat: 'waves', target: 40 },
  { id: 'wave_50', name: 'Cinquenta Ondas', description: 'Sobreviva ate a Wave 50.', rarity: 'EPIC', type: 'cumulative', stat: 'waves', target: 50 },
  { id: 'level_60', name: 'Nivel 60', description: 'Alcance o nivel 60.', rarity: 'EPIC', type: 'cumulative', stat: 'level', target: 60 },
  { id: 'level_75', name: 'Nivel 75', description: 'Alcance o nivel 75.', rarity: 'EPIC', type: 'cumulative', stat: 'level', target: 75 },
  { id: 'boss_25', name: 'Vinte e Cinco Chefes', description: 'Derrote 25 chefes.', rarity: 'EPIC', type: 'cumulative', stat: 'bosses', target: 25 },
  { id: 'miniboss_50', name: 'Cinquenta Minis', description: 'Derrote 50 mini-bosses.', rarity: 'EPIC', type: 'cumulative', stat: 'minibosses', target: 50 },
  { id: 'dmg_1000000', name: 'Um Milhao de Dano', description: 'Cause 1.000.000 de dano total.', rarity: 'EPIC', type: 'cumulative', stat: 'damageDealt', target: 1000000 },
  { id: 'dmg_2500000', name: 'Dois Milhoes de Dano', description: 'Cause 2.500.000 de dano total.', rarity: 'EPIC', type: 'cumulative', stat: 'damageDealt', target: 2500000 },
  { id: 'revive_10', name: 'Fantasma', description: 'Use 10 revives.', rarity: 'EPIC', type: 'cumulative', stat: 'revivesUsed', target: 10 },
  { id: 'kill_streak_20', name: 'Sequencia de 20', description: 'Mate 20 inimigos seguidos sem morrer.', rarity: 'EPIC', type: 'instant', test: g => (g.stats.killStreak || 0) >= 20 },
  { id: 'play_30', name: 'Viciado', description: 'Complete 30 partidas.', rarity: 'EPIC', type: 'cumulative', stat: 'matchesPlayed', target: 30 },
  { id: 'match_win_20', name: 'Vinte Vitorias', description: 'Venca 20 partidas.', rarity: 'EPIC', type: 'cumulative', stat: 'matchesWon', target: 20 },
  { id: 'headshot_100', name: 'Centenio', description: 'Acerte 100 headshots.', rarity: 'EPIC', type: 'cumulative', stat: 'headshots', target: 100 },
  { id: 'wave_60', name: 'Sessenta Ondas', description: 'Sobreviva ate a Wave 60.', rarity: 'EPIC', type: 'cumulative', stat: 'waves', target: 60 },
  { id: 'collect_250', name: 'Mega Colecionador', description: 'Colete 250 drops no chao.', rarity: 'EPIC', type: 'cumulative', stat: 'dropsCollected', target: 250 },
  { id: 'boss_solo', name: 'Solitario', description: 'Derrote um boss sem ajuda de bots.', rarity: 'EPIC', type: 'instant', test: g => (g.stats.bossSoloKills || 0) >= 1 },
  { id: 'kill_streak_15', name: 'Sequencia de 15', description: 'Mate 15 inimigos seguidos sem morrer.', rarity: 'EPIC', type: 'instant', test: g => (g.stats.killStreak || 0) >= 15 },
  { id: 'miniboss_40', name: 'Quarenta Minis', description: 'Derrote 40 mini-bosses.', rarity: 'EPIC', type: 'cumulative', stat: 'minibosses', target: 40 },
  { id: 'armors_6', name: 'Seis Armaduras', description: 'Adquira 6 armaduras diferentes.', rarity: 'EPIC', type: 'cumulative', stat: 'armorsOwned', target: 6 },
  { id: 'level_70', name: 'Nivel 70', description: 'Alcance o nivel 70.', rarity: 'EPIC', type: 'cumulative', stat: 'level', target: 70 },
  { id: 'match_win_15', name: 'Quinze Vitorias', description: 'Venca 15 partidas.', rarity: 'EPIC', type: 'cumulative', stat: 'matchesWon', target: 15 },
  { id: 'play_25', name: 'Fiel', description: 'Complete 25 partidas.', rarity: 'EPIC', type: 'cumulative', stat: 'matchesPlayed', target: 25 },
  { id: 'kills_600', name: 'Exterminador de Massa', description: 'Elimine 600 inimigos.', rarity: 'EPIC', type: 'cumulative', stat: 'kills', target: 600 },
  { id: 'money_500000', name: 'Magnata Extremo', description: 'Acumule R$500.000 em uma partida.', rarity: 'EPIC', type: 'cumulative', stat: 'moneyEarned', target: 500000 },
  { id: 'time_600', name: 'Decano', description: 'Sobreviva por 10 minutos em uma partida.', rarity: 'EPIC', type: 'instant', test: g => (g.stats.survivalTime || 0) >= 600 },

  { id: 'kills_1000', name: 'Mil Abates', description: 'Elimine 1.000 inimigos.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'kills', target: 1000 },
  { id: 'kills_1500', name: 'Massacre', description: 'Elimine 1.500 inimigos.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'kills', target: 1500 },
  { id: 'kills_2000', name: 'Furacao', description: 'Elimine 2.000 inimigos.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'kills', target: 2000 },
  { id: 'money_1000000', name: 'Bilionario', description: 'Acumule R$1.000.000 em uma partida.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'moneyEarned', target: 1000000 },
  { id: 'tokens_250', name: 'Duzentos e Cinquenta', description: 'Acumule 250 tokens.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'tokensEarned', target: 250 },
  { id: 'tokens_500', name: 'Token King', description: 'Acumule 500 tokens.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'tokensEarned', target: 500 },
  { id: 'wave_75', name: 'Setenta e Cinco Ondas', description: 'Sobreviva ate a Wave 75.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'waves', target: 75 },
  { id: 'wave_100', name: 'Mestre das Waves', description: 'Sobreviva ate a Wave 100.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'waves', target: 100 },
  { id: 'level_85', name: 'Nivel 85', description: 'Alcance o nivel 85.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'level', target: 85 },
  { id: 'level_100', name: 'Nivel 100', description: 'Alcance o nivel 100.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'level', target: 100 },
  { id: 'boss_50', name: 'Cinquenta Chefes', description: 'Derrote 50 chefes.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'bosses', target: 50 },
  { id: 'miniboss_100', name: 'Cem Minis', description: 'Derrote 100 mini-bosses.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'minibosses', target: 100 },
  { id: 'dmg_5000000', name: 'Cinco Milhoes de Dano', description: 'Cause 5.000.000 de dano total.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'damageDealt', target: 5000000 },
  { id: 'dmg_10000000', name: 'Dez Milhoes de Dano', description: 'Cause 10.000.000 de dano total.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'damageDealt', target: 10000000 },
  { id: 'kill_streak_30', name: 'Sequencia de 30', description: 'Mate 30 inimigos seguidos sem morrer.', rarity: 'LEGENDARY', type: 'instant', test: g => (g.stats.killStreak || 0) >= 30 },
  { id: 'play_50', name: 'Nao Para', description: 'Complete 50 partidas.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'matchesPlayed', target: 50 },
  { id: 'match_win_30', name: 'Trinta Vitorias', description: 'Venca 30 partidas.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'matchesWon', target: 30 },
  { id: 'headshot_250', name: 'Olho de Falco', description: 'Acerte 250 headshots.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'headshots', target: 250 },
  { id: 'collect_500', name: 'Tudo e Meu', description: 'Colete 500 drops no chao.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'dropsCollected', target: 500 },
  { id: 'revive_15', name: 'Renascido Eterno', description: 'Use 15 revives.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'revivesUsed', target: 15 },
  { id: 'wave_90', name: 'Noventa Ondas', description: 'Sobreviva ate a Wave 90.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'waves', target: 90 },
  { id: 'kills_1250', name: 'Destruidor', description: 'Elimine 1.250 inimigos.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'kills', target: 1250 },
  { id: 'armors_7', name: 'Sete Armaduras', description: 'Adquira 7 armaduras diferentes.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'armorsOwned', target: 7 },
  { id: 'boss_30', name: 'Trinta Chefes', description: 'Derrote 30 chefes.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'bosses', target: 30 },
  { id: 'match_win_25', name: 'Vinte e Cinco Vitorias', description: 'Venca 25 partidas.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'matchesWon', target: 25 },
  { id: 'headshot_150', name: 'Atirador de Elite', description: 'Acerte 150 headshots.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'headshots', target: 150 },
  { id: 'money_750000', name: 'Dono do Mundo', description: 'Acumule R$750.000 em uma partida.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'moneyEarned', target: 750000 },
  { id: 'play_40', name: 'Nao Pare', description: 'Complete 40 partidas.', rarity: 'LEGENDARY', type: 'cumulative', stat: 'matchesPlayed', target: 40 },

  { id: 'kills_2500', name: 'A Morte', description: 'Elimine 2.500 inimigos.', rarity: 'MYTHIC', type: 'cumulative', stat: 'kills', target: 2500 },
  { id: 'kills_3000', name: 'Pestilencia', description: 'Elimine 3.000 inimigos.', rarity: 'MYTHIC', type: 'cumulative', stat: 'kills', target: 3000 },
  { id: 'kills_5000', name: 'Deus da Guerra', description: 'Elimine 5.000 inimigos.', rarity: 'MYTHIC', type: 'cumulative', stat: 'kills', target: 5000 },
  { id: 'tokens_1000', name: 'Mil Tokens', description: 'Acumule 1.000 tokens.', rarity: 'MYTHIC', type: 'cumulative', stat: 'tokensEarned', target: 1000 },
  { id: 'wave_150', name: 'Cento e Cinquenta Ondas', description: 'Sobreviva ate a Wave 150.', rarity: 'MYTHIC', type: 'cumulative', stat: 'waves', target: 150 },
  { id: 'wave_200', name: 'Duzentas Ondas', description: 'Sobreviva ate a Wave 200.', rarity: 'MYTHIC', type: 'cumulative', stat: 'waves', target: 200 },
  { id: 'dmg_25000000', name: 'Vinte e Cinco Milhoes', description: 'Cause 25.000.000 de dano total.', rarity: 'MYTHIC', type: 'cumulative', stat: 'damageDealt', target: 25000000 },
  { id: 'dmg_50000000', name: 'Cinquenta Milhoes de Dano', description: 'Cause 50.000.000 de dano total.', rarity: 'MYTHIC', type: 'cumulative', stat: 'damageDealt', target: 50000000 },
  { id: 'kill_streak_50', name: 'Sequencia de 50', description: 'Mate 50 inimigos seguidos sem morrer.', rarity: 'MYTHIC', type: 'instant', test: g => (g.stats.killStreak || 0) >= 50 },
  { id: 'match_win_50', name: 'Cinquenta Vitorias', description: 'Venca 50 partidas.', rarity: 'MYTHIC', type: 'cumulative', stat: 'matchesWon', target: 50 },
  { id: 'play_100', name: 'Centenário', description: 'Complete 100 partidas.', rarity: 'MYTHIC', type: 'cumulative', stat: 'matchesPlayed', target: 100 },
  { id: 'boss_100', name: 'Cem Chefes', description: 'Derrote 100 chefes.', rarity: 'MYTHIC', type: 'cumulative', stat: 'bosses', target: 100 },
  { id: 'miniboss_200', name: 'Duzentos Minis', description: 'Derrote 200 mini-bosses.', rarity: 'MYTHIC', type: 'cumulative', stat: 'minibosses', target: 200 },
  { id: 'headshot_500', name: 'Lenda das Armas', description: 'Acerte 500 headshots.', rarity: 'MYTHIC', type: 'cumulative', stat: 'headshots', target: 500 },
  { id: 'revive_25', name: 'Além da Morte', description: 'Use 25 revives.', rarity: 'MYTHIC', type: 'cumulative', stat: 'revivesUsed', target: 25 },
  { id: 'collect_1000', name: 'Mega Colecionador', description: 'Colete 1.000 drops no chao.', rarity: 'MYTHIC', type: 'cumulative', stat: 'dropsCollected', target: 1000 },
  { id: 'level_100_max', name: 'Nivel Maximo', description: 'Alcance o nivel 100 e mantenha.', rarity: 'MYTHIC', type: 'instant', test: g => g.level >= 100 },
  { id: 'wave_125', name: 'Centro e Vinte e Cinco', description: 'Sobreviva ate a Wave 125.', rarity: 'MYTHIC', type: 'cumulative', stat: 'waves', target: 125 },
  { id: 'kills_4000', name: 'Genocida', description: 'Elimine 4.000 inimigos.', rarity: 'MYTHIC', type: 'cumulative', stat: 'kills', target: 4000 },
  { id: 'boss_75', name: 'Setenta e Cinco Chefes', description: 'Derrote 75 chefes.', rarity: 'MYTHIC', type: 'cumulative', stat: 'bosses', target: 75 },
  { id: 'match_win_40', name: 'Quarenta Vitorias', description: 'Venca 40 partidas.', rarity: 'MYTHIC', type: 'cumulative', stat: 'matchesWon', target: 40 },
  { id: 'tokens_750', name: 'Tokens Infinitos', description: 'Acumule 750 tokens.', rarity: 'MYTHIC', type: 'cumulative', stat: 'tokensEarned', target: 750 },
  { id: 'kills_3500', name: 'Extinto', description: 'Elimine 3.500 inimigos.', rarity: 'MYTHIC', type: 'cumulative', stat: 'kills', target: 3500 },
  { id: 'armors_8', name: 'Oito Armaduras', description: 'Adquira 8 armaduras diferentes.', rarity: 'MYTHIC', type: 'cumulative', stat: 'armorsOwned', target: 8 },
  { id: 'miniboss_150', name: 'Cento e Cinquenta Minis', description: 'Derrote 150 mini-bosses.', rarity: 'MYTHIC', type: 'cumulative', stat: 'minibosses', target: 150 },
  { id: 'play_75', name: 'Setenta e Cinco Partidas', description: 'Complete 75 partidas.', rarity: 'MYTHIC', type: 'cumulative', stat: 'matchesPlayed', target: 75 },

  { id: 'rebirth_1', name: 'Primeiro Rebirth', description: 'Realize seu primeiro rebirth.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 1 },
  { id: 'rebirth_2', name: 'Segundo Rebirth', description: 'Realize seu segundo rebirth.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 2 },
  { id: 'rebirth_3', name: 'Terceiro Rebirth', description: 'Realize seu terceiro rebirth.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 3 },
  { id: 'rebirth_5', name: 'Cinco Rebirths', description: 'Realize 5 rebirths.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 5 },
  { id: 'rebirth_10', name: 'Dez Rebirths', description: 'Realize 10 rebirths.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 10 },
  { id: 'dmg_100000000', name: 'Cem Milhoes de Dano', description: 'Cause 100.000.000 de dano total.', rarity: 'DIVINE', type: 'cumulative', stat: 'damageDealt', target: 100000000 },
  { id: 'kills_10000', name: 'Decimo Mil Abate', description: 'Elimine 10.000 inimigos.', rarity: 'DIVINE', type: 'cumulative', stat: 'kills', target: 10000 },
  { id: 'wave_300', name: 'Trezentas Ondas', description: 'Sobreviva ate a Wave 300.', rarity: 'DIVINE', type: 'cumulative', stat: 'waves', target: 300 },
  { id: 'match_win_100', name: 'Cem Vitorias', description: 'Venca 100 partidas.', rarity: 'DIVINE', type: 'cumulative', stat: 'matchesWon', target: 100 },
  { id: 'play_200', name: 'Viciado Total', description: 'Complete 200 partidas.', rarity: 'DIVINE', type: 'cumulative', stat: 'matchesPlayed', target: 200 },
  { id: 'kill_streak_100', name: 'Sequencia de 100', description: 'Mate 100 inimigos seguidos sem morrer.', rarity: 'DIVINE', type: 'instant', test: g => (g.stats.killStreak || 0) >= 100 },
  { id: 'boss_200', name: 'Duzentos Chefes', description: 'Derrote 200 chefes.', rarity: 'DIVINE', type: 'cumulative', stat: 'bosses', target: 200 },
  { id: 'tokens_2000', name: 'Dois Mil Tokens', description: 'Acumule 2.000 tokens.', rarity: 'DIVINE', type: 'cumulative', stat: 'tokensEarned', target: 2000 },
  { id: 'rebirth_7', name: 'Sete Rebirths', description: 'Realize 7 rebirths.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 7 },
  { id: 'wave_250', name: 'Duzentas e Cinquenta Ondas', description: 'Sobreviva ate a Wave 250.', rarity: 'DIVINE', type: 'cumulative', stat: 'waves', target: 250 },
  { id: 'headshot_1000', name: 'Mestre dos Headshots', description: 'Acerte 1.000 headshots.', rarity: 'DIVINE', type: 'cumulative', stat: 'headshots', target: 1000 },
  { id: 'collect_2000', name: 'Nada Escapa', description: 'Colete 2.000 drops no chao.', rarity: 'DIVINE', type: 'cumulative', stat: 'dropsCollected', target: 2000 },
  { id: 'boss_150', name: 'Cento e Cinquenta Chefes', description: 'Derrote 150 chefes.', rarity: 'DIVINE', type: 'cumulative', stat: 'bosses', target: 150 },
  { id: 'dmg_200000000', name: 'Duzentos Milhoes de Dano', description: 'Cause 200.000.000 de dano total.', rarity: 'DIVINE', type: 'cumulative', stat: 'damageDealt', target: 200000000 },
  { id: 'rebirth_8', name: 'Oito Rebirths', description: 'Realize 8 rebirths.', rarity: 'DIVINE', type: 'cumulative', stat: 'rebirths', target: 8 },
  { id: 'miniboss_300', name: 'Trezentos Minis', description: 'Derrote 300 mini-bosses.', rarity: 'DIVINE', type: 'cumulative', stat: 'minibosses', target: 300 },
  { id: 'match_win_75', name: 'Setenta e Cinco Vitorias', description: 'Venca 75 partidas.', rarity: 'DIVINE', type: 'cumulative', stat: 'matchesWon', target: 75 },
  { id: 'revive_50', name: 'Eterno Retorno', description: 'Use 50 revives.', rarity: 'DIVINE', type: 'cumulative', stat: 'revivesUsed', target: 50 },
  { id: 'kills_7500', name: 'Apocalipse', description: 'Elimine 7.500 inimigos.', rarity: 'DIVINE', type: 'cumulative', stat: 'kills', target: 7500 },
  { id: 'wave_400', name: 'Quatrocentas Ondas', description: 'Sobreviva ate a Wave 400.', rarity: 'DIVINE', type: 'cumulative', stat: 'waves', target: 400 },

  // Categoria secreta ??? — a mais rara e dificil de todas.
  // Progresso em 3 partes (barra X/3). Recompensa final: REVIVE INFINITO.
  {
    id: 'the_end_of_all_things',
    name: '???',
    description: 'Ninguem sabe ao certo. Dizem que envolve 1 bilhão de dano, 50.000 abates, 20 renascimentos... e a MINIGUN. Recompensa: REVIVE INFINITO.',
    rarity: '???',
    type: 'instant',
    target: 3,
    test: g => {
      if (!g || !g.stats) return false;
      const hasMinigun = !!(g.weapon && Array.isArray(g.weapon.inventory) && g.weapon.inventory.includes('minigun'));
      return g.getStatValue('damageDealt') >= 1000000000 &&
        g.getStatValue('kills') >= 50000 &&
        g.getStatValue('revivesUsed') >= 20 &&
        hasMinigun;
    },
    progress: g => {
      let done = 0;
      if (g.getStatValue('damageDealt') >= 1000000000) done++;
      if (g.getStatValue('kills') >= 50000) done++;
      const hasMinigun = !!(g.weapon && Array.isArray(g.weapon.inventory) && g.weapon.inventory.includes('minigun'));
      if (g.getStatValue('revivesUsed') >= 20 && hasMinigun) done++;
      return done;
    },
  },

  { id: 'death_10', name: 'Masoquista', description: 'Morra 10 vezes.', rarity: 'CURSED', type: 'cumulative', stat: 'deaths', target: 10 },
  { id: 'death_25', name: 'Errado', description: 'Morra 25 vezes.', rarity: 'CURSED', type: 'cumulative', stat: 'deaths', target: 25 },
  { id: 'death_50', name: 'Fracassado', description: 'Morra 50 vezes.', rarity: 'CURSED', type: 'cumulative', stat: 'deaths', target: 50 },
  { id: 'revive_20', name: 'Preguiçoso', description: 'Use 20 revives ao inves de progredir.', rarity: 'CURSED', type: 'cumulative', stat: 'revivesUsed', target: 20 },
  { id: 'match_loss_10', name: 'Perdedor Nato', description: 'Perca 10 partidas.', rarity: 'CURSED', type: 'cumulative', stat: 'matchesLost', target: 10 },
  { id: 'match_loss_25', name: 'Sem Chance', description: 'Perca 25 partidas.', rarity: 'CURSED', type: 'cumulative', stat: 'matchesLost', target: 25 },
  { id: 'money_spent_50000', name: 'Gastador', description: 'Gaste R$50.000 na loja no total.', rarity: 'CURSED', type: 'cumulative', stat: 'moneySpent', target: 50000 },
  { id: 'money_spent_100000', name: 'Irresponsavel', description: 'Gaste R$100.000 na loja no total.', rarity: 'CURSED', type: 'cumulative', stat: 'moneySpent', target: 100000 },
  { id: 'wave_5_loss', name: 'Incompetente', description: 'Morra antes da Wave 5.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.earlyDeaths || 0) >= 1 },
  { id: 'idle_300', name: 'Ocioso', description: 'Fique 5 minutos sem se mover em partida.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.idleTime || 0) >= 300 },
  { id: 'empty_weapon', name: 'Sem Balas', description: 'Tente atirar com arma sem municao 5 vezes.', rarity: 'CURSED', type: 'cumulative', stat: 'emptyShots', target: 5 },
  { id: 'no_coins_wave', name: 'Pobre', description: 'Complete uma wave sem coletar nenhuma moeda.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.poorWaves || 0) >= 1 },
  { id: 'death_streak_3', name: 'Morta Vivo', description: 'Morra 3 vezes seguidas.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.deathStreak || 0) >= 3 },
  { id: 'money_0_end', name: 'Quebrado', description: 'Termine uma partida com R$0.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.brokeEnds || 0) >= 1 },
  { id: 'dmg_0_match', name: 'Inofensivo', description: 'Termine uma partida com 0 de dano.', rarity: 'CURSED', type: 'instant', test: g => (g.stats.zeroDmgMatches || 0) >= 1 },
  { id: 'death_100', name: 'Lenda das Mortes', description: 'Morra 100 vezes.', rarity: 'CURSED', type: 'cumulative', stat: 'deaths', target: 100 },

// ===== CONQUISTAS DOS MODOS DE JOGO =====
  { id: 'mode_normal', name: 'Modo Normal', description: 'Jogue uma partida no modo Normal.', rarity: 'COMMON', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.normal >= 1) },
  { id: 'mode_reverse', name: 'Modo Reverse', description: 'Jogue uma partida no modo Reverse.', rarity: 'UNCOMMON', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.reverse >= 1) },
  { id: 'mode_turbo', name: 'Modo Turbo', description: 'Jogue uma partida no modo Turbo.', rarity: 'UNCOMMON', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.turbo >= 1) },
  { id: 'mode_mini', name: 'Modo Mini', description: 'Jogue uma partida no modo Mini.', rarity: 'RARE', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.mini >= 1) },
  { id: 'mode_giant', name: 'Modo Gigante', description: 'Jogue uma partida no modo Gigante.', rarity: 'RARE', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.giant >= 1) },
  { id: 'mode_moon', name: 'Modo Gravidade Zero', description: 'Jogue uma partida no modo Gravidade Zero.', rarity: 'RARE', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.moon >= 1) },
  { id: 'mode_vampire', name: 'Modo Vampiro', description: 'Jogue uma partida no modo Vampiro.', rarity: 'EPIC', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.vampire >= 1) },
  { id: 'mode_gold', name: 'Modo Dourado', description: 'Jogue uma partida no modo Dourado.', rarity: 'EPIC', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.gold >= 1) },
  { id: 'mode_ghost', name: 'Modo Fantasma', description: 'Jogue uma partida no modo Fantasma.', rarity: 'EPIC', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.ghost >= 1) },
  { id: 'mode_horde', name: 'Modo Horda', description: 'Jogue uma partida no modo Horda.', rarity: 'LEGENDARY', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.horde >= 1) },
  { id: 'mode_chaos', name: 'Modo Chaos Mode', description: 'Jogue uma partida no modo Chaos Mode.', rarity: 'LEGENDARY', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.chaos >= 1) },
  { id: 'mode_oneshot', name: 'Modo One Shot', description: 'Jogue uma partida no modo One Shot.', rarity: 'MYTHIC', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.oneshot >= 1) },
  { id: 'mode_bossrush', name: 'Modo Boss Rush', description: 'Jogue uma partida no modo Boss Rush.', rarity: 'DIVINE', type: 'instant', test: g => !!(g.stats && g.stats.modePlays && g.stats.modePlays.bossrush >= 1) },
  { id: 'mode_all', name: 'Colecionador de Modos', description: 'Jogue pelo menos uma partida em TODOS os 13 modos.', rarity: 'DIVINE', type: 'instant', test: g => { if (!(g.stats && g.stats.modePlays)) return false; const ids = ['normal','reverse','turbo','mini','giant','moon','vampire','gold','ghost','horde','chaos','oneshot','bossrush']; return ids.every(id => (g.stats.modePlays[id] || 0) >= 1); } },
  { id: 'revive_inf_1', name: 'Caminho do Retorno', description: 'Use 10 revives no total.', rarity: 'EPIC', type: 'instant', test: g => (g.stats && g.stats.revivesUsed || 0) >= 10 },
  { id: 'revive_inf_2', name: 'Voltando da Morte', description: 'Venca uma partida tendo usado revive nela.', rarity: 'LEGENDARY', type: 'instant', test: g => (g.stats && g.stats.reviveWins || 0) >= 1 },
  { id: 'revive_inf_3', name: 'Nove Vidas', description: 'Use 25 revives no total.', rarity: 'MYTHIC', type: 'instant', test: g => (g.stats && g.stats.revivesUsed || 0) >= 25 },
  { id: 'revive_inf_4', name: 'Imortal de Verdade', description: 'Venca 3 partidas usando revive em cada.', rarity: 'DIVINE', type: 'instant', test: g => (g.stats && g.stats.reviveWins || 0) >= 3 },
  { id: 'revive_inf_5', name: 'Alem da Vida', description: 'Use 50 revives e venca 5 partidas com revive. Recompensa: REVIVE INFINITO.', rarity: 'DIVINE', type: 'instant', test: g => (g.stats && g.stats.revivesUsed || 0) >= 50 && (g.stats && g.stats.reviveWins || 0) >= 5 },
];

const RARITY_REWARDS = {
  COMMON: { money: 250 },
  UNCOMMON: { money: 500 },
  RARE: { money: 1500, tokens: 1 },
  EPIC: { money: 3000, tokens: 2 },
  LEGENDARY: { money: 7500, tokens: 4 },
  MYTHIC: { money: 15000, tokens: 8 },
  DIVINE: { money: 40000, tokens: 15 },
  CURSED: { money: 1000, tokens: 3 }
};

for (const def of ACHIEVEMENTS) {
  def.reward = { ...RARITY_REWARDS[def.rarity] };
}
