// Catalogo completo da loja gerado a partir da especificacao.
// Cada item: item (id unico), name, desc, cost, currency, icon, grant.
// grant.type: 'weapon' | 'armorHp' | 'ammo' | 'revive' | 'flag'
// purchasable: false => aparece na loja mas nao pode ser comprado.

import { WEAPONS } from './weapon.js';

const CATALOG_WEAPONS = [
  ['glock', 'Glock', 30, 'hitscan', 45, 0.44],
  ['desert-eagle', 'Desert Eagle', 30, 'hitscan', 45, 0.44],
  ['uzi', 'Uzi', 24, 'hitscan', 50, 0.18],
  ['mp5', 'MP5', 24, 'hitscan', 50, 0.18],
  ['p90', 'P90', 24, 'hitscan', 50, 0.18],
  ['vector', 'Vector', 25, 'hitscan', 50, 0.18],
  ['m4a1', 'M4A1', 36, 'hitscan', 70, 0.26],
  ['scar-h', 'SCAR-H', 37, 'hitscan', 70, 0.26],
  ['famas', 'FAMAS', 36, 'hitscan', 70, 0.26],
  ['aug', 'AUG', 37, 'hitscan', 70, 0.26],
  ['g36', 'G36', 36, 'hitscan', 70, 0.26],
  ['m16', 'M16', 36, 'hitscan', 70, 0.26],
  ['ak-74', 'AK-74', 37, 'hitscan', 70, 0.26],
  ['galil', 'Galil', 36, 'hitscan', 70, 0.26],
  ['tar-21', 'TAR-21', 37, 'hitscan', 70, 0.26],
  ['spas-12', 'SPAS-12', 57, 'hitscan', 30, 1.5],
  ['m870', 'M870', 56, 'hitscan', 30, 1.5],
  ['double-barrel', 'Double Barrel', 56, 'hitscan', 30, 1.5],
  ['aa-12', 'AA-12', 59, 'hitscan', 30, 1.5],
  ['s12k', 'S12K', 59, 'hitscan', 30, 1.5],
  ['kar98k', 'Kar98k', 99, 'hitscan', 150, 3.6],
  ['m24', 'M24', 100, 'hitscan', 150, 3.6],
  ['awp', 'AWP', 106, 'hitscan', 150, 3.6],
  ['barrett', 'Barrett', 112, 'hitscan', 150, 3.6],
  ['dragunov', 'Dragunov', 104, 'hitscan', 150, 3.6],
  ['railgun', 'Railgun', 99, 'hitscan', 90, 2.0],
  ['plasma-gun', 'Plasma Gun', 104, 'hitscan', 90, 2.0],
  ['laser-rifle', 'Laser Rifle', 108, 'hitscan', 90, 2.0],
  ['rocket-launcher', 'Rocket Launcher', 125, 'projectile', 80, 7.0],
  ['bazuca', 'Bazuca', 123, 'projectile', 80, 7.0],
  ['grenade-launcher', 'Grenade Launcher', 121, 'projectile', 80, 7.0],
  ['crossbow', 'Crossbow', 39, 'ranged', 90, 1.8],
  ['heavy-crossbow', 'Heavy Crossbow', 40, 'ranged', 90, 1.8],
  ['flamethrower', 'Flamethrower', 79, 'hitscan', 60, 1.2],
  ['ice-gun', 'Ice Gun', 81, 'hitscan', 60, 1.2],
  ['thunder-gun', 'Thunder Gun', 85, 'hitscan', 60, 1.2],
  ['void-gun', 'Void Gun', 103, 'hitscan', 60, 1.2],
  ['golden-gun', 'Golden Gun', 39, 'hitscan', 45, 0.44],
  ['plasma-shotgun', 'Plasma Shotgun', 101, 'hitscan', 90, 2.0],
  ['heavy-rifle', 'Heavy Rifle', 40, 'hitscan', 70, 0.26],
  ['tactical-smg', 'Tactical SMG', 25, 'hitscan', 50, 0.18],
  ['combat-rifle', 'Combat Rifle', 38, 'hitscan', 70, 0.26],
  ['burst-rifle', 'Burst Rifle', 37, 'hitscan', 70, 0.26],
  ['auto-sniper', 'Auto Sniper', 109, 'hitscan', 150, 3.6],
  ['hand-cannon', 'Hand Cannon', 36, 'hitscan', 45, 0.44],
  ['energy-cannon', 'Energy Cannon', 106, 'hitscan', 90, 2.0],
  ['void-blaster', 'Void Blaster', 107, 'hitscan', 60, 1.2],
  ['mini-rocket', 'Mini Rocket', 121, 'projectile', 80, 7.0],
  ['heavy-minigun', 'Heavy Minigun', 45, 'hitscan', 70, 0.26],
  ['hyper-gun', 'Hyper Gun', 112, 'hitscan', 60, 1.2]
];

for (const [sid, name, dmg, type, range, cooldown] of CATALOG_WEAPONS) {
  if (!WEAPONS[sid]) {
    WEAPONS[sid] = { name: name.toUpperCase(), damage: dmg, type, range, cooldown };
  }
}

export const SHOP_SECTIONS = [
  {
    id: 'armas', icon: '🔫', title: 'ARMAS', currency: 'money',
    items: [
  { item: 'brick', name: 'Brick (Tijolo)', desc: 'Arremessável · 80-90 de dano · CD 15s · 5 unidades', cost: 15, currency: 'money', icon: '🧱', grant: { type: 'ammo', weapon: 'brick', amount: 5 } },
  { item: 'ak47', name: 'AK-47', desc: 'Rifle de assalto', cost: 3000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'ak47' } },
  { item: 'weapon-glock', name: 'Glock', desc: 'Pistola', cost: 750, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'glock' } },
  { item: 'weapon-desert-eagle', name: 'Desert Eagle', desc: 'Pistola pesada', cost: 1500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'desert-eagle' } },
  { item: 'weapon-uzi', name: 'Uzi', desc: 'Submetralhadora', cost: 2000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'uzi' } },
  { item: 'weapon-mp5', name: 'MP5', desc: 'Submetralhadora', cost: 2500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'mp5' } },
  { item: 'weapon-p90', name: 'P90', desc: 'Submetralhadora', cost: 3000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'p90' } },
  { item: 'weapon-vector', name: 'Vector', desc: 'SMG rápida', cost: 3500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'vector' } },
  { item: 'weapon-m4a1', name: 'M4A1', desc: 'Rifle de assalto', cost: 4000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'm4a1' } },
  { item: 'weapon-scar-h', name: 'SCAR-H', desc: 'Rifle pesado', cost: 6000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'scar-h' } },
  { item: 'weapon-famas', name: 'FAMAS', desc: 'Rifle de assalto', cost: 4500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'famas' } },
  { item: 'weapon-aug', name: 'AUG', desc: 'Rifle de assalto', cost: 5000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'aug' } },
  { item: 'weapon-g36', name: 'G36', desc: 'Rifle de assalto', cost: 4750, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'g36' } },
  { item: 'weapon-m16', name: 'M16', desc: 'Rifle de assalto', cost: 4250, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'm16' } },
  { item: 'weapon-ak-74', name: 'AK-74', desc: 'Rifle de assalto', cost: 5250, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'ak-74' } },
  { item: 'weapon-galil', name: 'Galil', desc: 'Rifle de assalto', cost: 3750, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'galil' } },
  { item: 'weapon-tar-21', name: 'TAR-21', desc: 'Rifle de assalto', cost: 5500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'tar-21' } },
  { item: 'weapon-spas-12', name: 'SPAS-12', desc: 'Escopeta', cost: 4500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'spas-12' } },
  { item: 'weapon-m870', name: 'M870', desc: 'Escopeta', cost: 3000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'm870' } },
  { item: 'weapon-double-barrel', name: 'Double Barrel', desc: 'Escopeta dupla', cost: 2250, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'double-barrel' } },
  { item: 'weapon-aa-12', name: 'AA-12', desc: 'Escopeta automática', cost: 7000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'aa-12' } },
  { item: 'weapon-s12k', name: 'S12K', desc: 'Escopeta automática', cost: 6500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 's12k' } },
  { item: 'weapon-kar98k', name: 'Kar98k', desc: 'Rifle de precisão', cost: 4000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'kar98k' } },
  { item: 'weapon-m24', name: 'M24', desc: 'Rifle de precisão', cost: 5000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'm24' } },
  { item: 'weapon-awp', name: 'AWP', desc: 'Rifle sniper', cost: 10000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'awp' } },
  { item: 'weapon-barrett', name: 'Barrett', desc: 'Sniper pesado', cost: 15000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'barrett' } },
  { item: 'weapon-dragunov', name: 'Dragunov', desc: 'Sniper semiautomático', cost: 8000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'dragunov' } },
  { item: 'weapon-railgun', name: 'Railgun', desc: 'Rifle de energia', cost: 20000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'railgun' } },
  { item: 'weapon-plasma-gun', name: 'Plasma Gun', desc: 'Arma energética', cost: 25000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'plasma-gun' } },
  { item: 'weapon-laser-rifle', name: 'Laser Rifle', desc: 'Rifle laser', cost: 30000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'laser-rifle' } },
  { item: 'weapon-rocket-launcher', name: 'Rocket Launcher', desc: 'Lançador', cost: 12000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'rocket-launcher' } },
  { item: 'weapon-bazuca', name: 'Bazuca', desc: 'Explosiva', cost: 10000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'bazuca' } },
  { item: 'weapon-grenade-launcher', name: 'Grenade Launcher', desc: 'Lançador', cost: 9000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'grenade-launcher' } },
  { item: 'weapon-crossbow', name: 'Crossbow', desc: 'Besta', cost: 3500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'crossbow' } },
  { item: 'weapon-heavy-crossbow', name: 'Heavy Crossbow', desc: 'Besta pesada', cost: 6000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'heavy-crossbow' } },
  { item: 'weapon-flamethrower', name: 'Flamethrower', desc: 'Lança-chamas', cost: 11000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'flamethrower' } },
  { item: 'weapon-ice-gun', name: 'Ice Gun', desc: 'Arma congelante', cost: 14000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'ice-gun' } },
  { item: 'weapon-thunder-gun', name: 'Thunder Gun', desc: 'Arma elétrica', cost: 18000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'thunder-gun' } },
  { item: 'weapon-void-gun', name: 'Void Gun', desc: 'Arma Void', cost: 40000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'void-gun' } },
  { item: 'weapon-golden-gun', name: 'Golden Gun', desc: 'Pistola dourada', cost: 25000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'golden-gun' } },
  { item: 'weapon-plasma-shotgun', name: 'Plasma Shotgun', desc: 'Escopeta energética', cost: 22000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'plasma-shotgun' } },
  { item: 'weapon-heavy-rifle', name: 'Heavy Rifle', desc: 'Rifle pesado', cost: 13000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'heavy-rifle' } },
  { item: 'weapon-tactical-smg', name: 'Tactical SMG', desc: 'SMG tática', cost: 5500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'tactical-smg' } },
  { item: 'weapon-combat-rifle', name: 'Combat Rifle', desc: 'Rifle de combate', cost: 7500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'combat-rifle' } },
  { item: 'weapon-burst-rifle', name: 'Burst Rifle', desc: 'Rifle de rajada', cost: 6250, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'burst-rifle' } },
  { item: 'weapon-auto-sniper', name: 'Auto Sniper', desc: 'Sniper automático', cost: 12500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'auto-sniper' } },
  { item: 'weapon-hand-cannon', name: 'Hand Cannon', desc: 'Canhão portátil', cost: 17500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'hand-cannon' } },
  { item: 'weapon-energy-cannon', name: 'Energy Cannon', desc: 'Canhão energético', cost: 27500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'energy-cannon' } },
  { item: 'weapon-void-blaster', name: 'Void Blaster', desc: 'Blaster Void', cost: 45000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'void-blaster' } },
  { item: 'weapon-mini-rocket', name: 'Mini Rocket', desc: 'Lançador compacto', cost: 8500, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'mini-rocket' } },
  { item: 'weapon-heavy-minigun', name: 'Heavy Minigun', desc: 'Minigun pesada', cost: 25000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'heavy-minigun' } },
  { item: 'weapon-hyper-gun', name: 'Hyper Gun', desc: 'Arma experimental', cost: 50000, currency: 'money', icon: '🔫', grant: { type: 'weapon', id: 'hyper-gun' } }
    ]
  },
  {
    id: 'boosts', icon: '⚡', title: 'BOOSTS', currency: 'tokens',
    items: [
  { item: 'boost-velocidade-ii', name: 'Velocidade II', desc: '+75% velocidade · 60s', cost: 2, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'boost_velocidade_ii' } },
  { item: 'boost-velocidade-iii', name: 'Velocidade III', desc: '+100% velocidade · 60s', cost: 3, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'boost_velocidade_iii' } },
  { item: 'boost-vida-maxima-ii', name: 'Vida Máxima II', desc: '+200 HP', cost: 2, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_vida_maxima_ii' } },
  { item: 'boost-vida-maxima-iii', name: 'Vida Máxima III', desc: '+300 HP', cost: 3, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_vida_maxima_iii' } },
  { item: 'boost-defesa', name: 'Defesa', desc: '+25% defesa · 60s', cost: 2, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_defesa' } },
  { item: 'boost-defesa-ii', name: 'Defesa II', desc: '+50% defesa · 60s', cost: 4, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_defesa_ii' } },
  { item: 'boost-dano', name: 'Dano', desc: '+25% dano · 60s', cost: 2, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_dano' } },
  { item: 'boost-dano-ii', name: 'Dano II', desc: '+50% dano · 60s', cost: 4, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_dano_ii' } },
  { item: 'boost-precisao', name: 'Precisão', desc: '+30% precisão · 60s', cost: 2, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'boost_precisao' } },
  { item: 'boost-precisao-ii', name: 'Precisão II', desc: '+60% precisão · 60s', cost: 4, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'boost_precisao_ii' } },
  { item: 'boost-recarga', name: 'Recarga', desc: '+30% recarga · 60s', cost: 3, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_recarga' } },
  { item: 'boost-recarga-ii', name: 'Recarga II', desc: '+60% recarga · 60s', cost: 5, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_recarga_ii' } },
  { item: 'boost-sprint', name: 'Sprint', desc: '+100% corrida · 30s', cost: 2, currency: 'tokens', icon: '🏃', grant: { type: 'flag', key: 'boost_sprint' } },
  { item: 'boost-escudo', name: 'Escudo', desc: '100 HP escudo · 60s', cost: 3, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_escudo' } },
  { item: 'boost-escudo-ii', name: 'Escudo II', desc: '250 HP escudo · 60s', cost: 6, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_escudo_ii' } },
  { item: 'boost-regeneracao', name: 'Regeneração', desc: '+10 HP/s · 30s', cost: 3, currency: 'tokens', icon: '💚', grant: { type: 'flag', key: 'boost_regeneracao' } },
  { item: 'boost-regeneracao-ii', name: 'Regeneração II', desc: '+25 HP/s · 30s', cost: 6, currency: 'tokens', icon: '💚', grant: { type: 'flag', key: 'boost_regeneracao_ii' } },
  { item: 'boost-dano-critico', name: 'Dano Crítico', desc: '+25% crítico · 60s', cost: 4, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_dano_critico' } },
  { item: 'boost-dano-critico-ii', name: 'Dano Crítico II', desc: '+50% crítico · 60s', cost: 7, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_dano_critico_ii' } },
  { item: 'boost-coletor', name: 'Coletor', desc: 'alcance coleta +100% · 60s', cost: 2, currency: 'tokens', icon: '🧲', grant: { type: 'flag', key: 'boost_coletor' } },
  { item: 'boost-fortuna', name: 'Fortuna', desc: '+50% dinheiro · 60s', cost: 4, currency: 'tokens', icon: '🪙', grant: { type: 'flag', key: 'boost_fortuna' } },
  { item: 'boost-fortuna-ii', name: 'Fortuna II', desc: '+100% dinheiro · 60s', cost: 7, currency: 'tokens', icon: '🪙', grant: { type: 'flag', key: 'boost_fortuna_ii' } },
  { item: 'boost-cura', name: 'Cura', desc: 'recupera 100 HP', cost: 2, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_cura' } },
  { item: 'boost-cura-ii', name: 'Cura II', desc: 'recupera 250 HP', cost: 4, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_cura_ii' } },
  { item: 'boost-furia', name: 'Fúria', desc: '+100% dano · 20s', cost: 5, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_furia' } },
  { item: 'boost-resistencia', name: 'Resistência', desc: 'resist. lentidão · 60s', cost: 3, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'boost_resistencia' } },
  { item: 'boost-reflexo', name: 'Reflexo', desc: '+50% reação · 60s', cost: 3, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_reflexo' } },
  { item: 'boost-invisibilidade', name: 'Invisibilidade', desc: 'invisível · 15s', cost: 8, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'boost_invisibilidade' } },
  { item: 'boost-invulnerabilidade', name: 'Invulnerabilidade', desc: 'sem dano · 5s', cost: 10, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_invulnerabilidade' } },
  { item: 'boost-super-velocidade', name: 'Super Velocidade', desc: '+150% vel · 30s', cost: 6, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'boost_super_velocidade' } },
  { item: 'boost-super-dano', name: 'Super Dano', desc: '+150% dano · 30s', cost: 8, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_super_dano' } },
  { item: 'boost-super-vida', name: 'Super Vida', desc: '+500 HP máx', cost: 5, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_super_vida' } },
  { item: 'boost-super-recarga', name: 'Super Recarga', desc: '+100% recarga · 30s', cost: 8, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_super_recarga' } },
  { item: 'boost-mira-perfeita', name: 'Mira Perfeita', desc: 'precisão máx · 30s', cost: 7, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'boost_mira_perfeita' } },
  { item: 'boost-mega-coletor', name: 'Mega Coletor', desc: 'alcance +300% · 60s', cost: 5, currency: 'tokens', icon: '🧲', grant: { type: 'flag', key: 'boost_mega_coletor' } },
  { item: 'boost-mega-fortuna', name: 'Mega Fortuna', desc: '+200% dinheiro · 60s', cost: 10, currency: 'tokens', icon: '🪙', grant: { type: 'flag', key: 'boost_mega_fortuna' } },
  { item: 'boost-cura-total', name: 'Cura Total', desc: 'recupera 100% HP', cost: 8, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'boost_cura_total' } },
  { item: 'boost-barreira', name: 'Barreira', desc: '500 HP escudo · 30s', cost: 9, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'boost_barreira' } },
  { item: 'boost-berserker', name: 'Berserker', desc: '+200% dano · 15s', cost: 10, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'boost_berserker' } },
  { item: 'boost-flash', name: 'Flash', desc: '+300% vel · 10s', cost: 12, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'boost_flash' } },
  { item: 'boost-overcharge', name: 'Overcharge', desc: '+200% recarga · 20s', cost: 10, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_overcharge' } },
  { item: 'boost-regen-suprema', name: 'Regen Suprema', desc: '+50 HP/s · 30s', cost: 10, currency: 'tokens', icon: '💚', grant: { type: 'flag', key: 'boost_regen_suprema' } },
  { item: 'boost-headshot', name: 'Headshot', desc: '+100% crítico · 30s', cost: 9, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'boost_headshot' } },
  { item: 'boost-fortaleza', name: 'Fortaleza', desc: '+100% defesa · 30s', cost: 12, currency: 'tokens', icon: '🪙', grant: { type: 'flag', key: 'boost_fortaleza' } },
  { item: 'boost-fase', name: 'Fase', desc: 'atravessa obstáculos · 10s', cost: 10, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'boost_fase' } },
  { item: 'boost-explosivo', name: 'Explosivo', desc: 'ataques AoE · 30s', cost: 8, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'boost_explosivo' } },
  { item: 'boost-congelante', name: 'Congelante', desc: 'ataques desaceleram · 30s', cost: 7, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'boost_congelante' } },
  { item: 'boost-eletrificado', name: 'Eletrificado', desc: 'ataques chocam · 30s', cost: 9, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'boost_eletrificado' } },
  { item: 'boost-void-boost', name: 'Void Boost', desc: '+500 HP e +100% vel · 30s', cost: 15, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'boost_void_boost' } },
  { item: 'boost-boost-supremo', name: 'Boost Supremo', desc: '+100% tudo · 30s', cost: 20, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'boost_boost_supremo' } }
    ]
  },
  {
    id: 'ammo', icon: '📦', title: 'MUNIÇÕES', currency: 'money',
    items: [
  { item: 'ammo-pistola', name: 'Munição Pistola', desc: '50 tiros', cost: 100, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'pistola', amount: 50 } },
  { item: 'ammo-pistola', name: 'Munição Pistola+', desc: '100 tiros', cost: 180, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'pistola', amount: 100 } },
  { item: 'ammo-uzi', name: 'Munição SMG', desc: '100 tiros', cost: 250, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'uzi', amount: 100 } },
  { item: 'ammo-uzi', name: 'Munição SMG+', desc: '250 tiros', cost: 550, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'uzi', amount: 250 } },
  { item: 'ammo-m4a1', name: 'Munição Rifle', desc: '100 tiros', cost: 350, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm4a1', amount: 100 } },
  { item: 'ammo-m4a1', name: 'Munição Rifle+', desc: '250 tiros', cost: 750, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm4a1', amount: 250 } },
  { item: 'ammo-ak47', name: 'Munição AK', desc: '100 tiros', cost: 400, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'ak47', amount: 100 } },
  { item: 'ammo-ak47', name: 'Munição AK+', desc: '250 tiros', cost: 850, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'ak47', amount: 250 } },
  { item: 'ammo-m16', name: 'Munição M4', desc: '100 tiros', cost: 375, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm16', amount: 100 } },
  { item: 'ammo-m16', name: 'Munição M4+', desc: '250 tiros', cost: 800, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm16', amount: 250 } },
  { item: 'ammo-m870', name: 'Munição Escopeta', desc: '25 tiros', cost: 300, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm870', amount: 25 } },
  { item: 'ammo-m870', name: 'Munição Escopeta+', desc: '50 tiros', cost: 550, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'm870', amount: 50 } },
  { item: 'ammo-sniper', name: 'Munição Sniper', desc: '10 tiros', cost: 288, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'sniper', amount: 10 } },
  { item: 'ammo-sniper', name: 'Munição Sniper+', desc: '25 tiros', cost: 650, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'sniper', amount: 25 } },
  { item: 'ammo-awp', name: 'Munição AWP', desc: '10 tiros', cost: 500, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'awp', amount: 10 } },
  { item: 'ammo-awp', name: 'Munição AWP+', desc: '25 tiros', cost: 1100, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'awp', amount: 25 } },
  { item: 'ammo-rocket-launcher', name: 'Munição Foguete', desc: '5 tiros', cost: 350, currency: 'money', icon: '🚀', grant: { type: 'ammo', weapon: 'rocket-launcher', amount: 5 } },
  { item: 'ammo-rocket-launcher', name: 'Munição Foguete+', desc: '15 tiros', cost: 900, currency: 'money', icon: '🚀', grant: { type: 'ammo', weapon: 'rocket-launcher', amount: 15 } },
  { item: 'ammo-bazuca', name: 'Munição Bazuca', desc: '100 tiros', cost: 575, currency: 'money', icon: '🚀', grant: { type: 'ammo', weapon: 'bazuca', amount: 100 } },
  { item: 'ammo-chicken_gun', name: 'Munição Chicken', desc: '10 tiros', cost: 58, currency: 'money', icon: '🐔', grant: { type: 'ammo', weapon: 'chicken_gun', amount: 10 } },
  { item: 'ammo-chicken_gun', name: 'Munição Chicken+', desc: '50 tiros', cost: 250, currency: 'money', icon: '🐔', grant: { type: 'ammo', weapon: 'chicken_gun', amount: 50 } },
  { item: 'ammo-laser-rifle', name: 'Munição Laser', desc: '50 tiros', cost: 1000, currency: 'money', icon: '⚡', grant: { type: 'ammo', weapon: 'laser-rifle', amount: 50 } },
  { item: 'ammo-laser-rifle', name: 'Munição Laser+', desc: '150 tiros', cost: 2500, currency: 'money', icon: '⚡', grant: { type: 'ammo', weapon: 'laser-rifle', amount: 150 } },
  { item: 'ammo-flamethrower', name: 'Munição Flame', desc: '100 unid.', cost: 900, currency: 'money', icon: '🔥', grant: { type: 'ammo', weapon: 'flamethrower', amount: 100 } },
  { item: 'ammo-flamethrower', name: 'Munição Flame+', desc: '300 unid.', cost: 2200, currency: 'money', icon: '🔥', grant: { type: 'ammo', weapon: 'flamethrower', amount: 300 } },
  { item: 'ammo-ice-gun', name: 'Munição Ice', desc: '50 tiros', cost: 1200, currency: 'money', icon: '❄️', grant: { type: 'ammo', weapon: 'ice-gun', amount: 50 } },
  { item: 'ammo-ice-gun', name: 'Munição Ice+', desc: '150 tiros', cost: 3000, currency: 'money', icon: '❄️', grant: { type: 'ammo', weapon: 'ice-gun', amount: 150 } },
  { item: 'ammo-void-gun', name: 'Munição Void', desc: '25 tiros', cost: 3500, currency: 'money', icon: '🕳️', grant: { type: 'ammo', weapon: 'void-gun', amount: 25 } },
  { item: 'ammo-void-gun', name: 'Munição Void+', desc: '100 tiros', cost: 10000, currency: 'money', icon: '🕳️', grant: { type: 'ammo', weapon: 'void-gun', amount: 100 } },
  { item: 'ammo-railgun', name: 'Munição Diamante', desc: '50 tiros', cost: 2500, currency: 'money', icon: '💎', grant: { type: 'ammo', weapon: 'railgun', amount: 50 } },
  { item: 'ammo-golden-gun', name: 'Munição Ouro', desc: '100 tiros', cost: 1500, currency: 'money', icon: '🟡', grant: { type: 'ammo', weapon: 'golden-gun', amount: 100 } },
  { item: 'ammo-heavy-rifle', name: 'Munição Ferro', desc: '100 tiros', cost: 1000, currency: 'money', icon: '⚪', grant: { type: 'ammo', weapon: 'heavy-rifle', amount: 100 } },
  { item: 'ammo-combat-rifle', name: 'Munição Couro', desc: '100 tiros', cost: 750, currency: 'money', icon: '🟡', grant: { type: 'ammo', weapon: 'combat-rifle', amount: 100 } },
  { item: 'ammo-grenade-launcher', name: 'Munição Explosiva', desc: '25 tiros', cost: 1500, currency: 'money', icon: '💥', grant: { type: 'ammo', weapon: 'grenade-launcher', amount: 25 } },
  { item: 'ammo-grenade-launcher', name: 'Munição Explosiva+', desc: '75 tiros', cost: 4000, currency: 'money', icon: '💥', grant: { type: 'ammo', weapon: 'grenade-launcher', amount: 75 } },
  { item: 'ammo-thunder-gun', name: 'Munição Shock', desc: '25 tiros', cost: 1800, currency: 'money', icon: '⚡', grant: { type: 'ammo', weapon: 'thunder-gun', amount: 25 } },
  { item: 'ammo-thunder-gun', name: 'Munição Shock+', desc: '75 tiros', cost: 4500, currency: 'money', icon: '⚡', grant: { type: 'ammo', weapon: 'thunder-gun', amount: 75 } },
  { item: 'ammo-crossbow', name: 'Munição Teleport', desc: '10 cargas', cost: 2000, currency: 'money', icon: '🌀', grant: { type: 'ammo', weapon: 'crossbow', amount: 10 } },
  { item: 'ammo-kar98k', name: 'Munição Precisa', desc: '50 tiros', cost: 1500, currency: 'money', icon: '📦', grant: { type: 'ammo', weapon: 'kar98k', amount: 50 } },
  { item: 'ammo-flamethrower', name: 'Munição Incendiária', desc: '50 tiros', cost: 2000, currency: 'money', icon: '🔥', grant: { type: 'ammo', weapon: 'flamethrower', amount: 50 } },
  { item: 'ammo-ice-gun', name: 'Munição Congelante', desc: '50 tiros', cost: 2000, currency: 'money', icon: '🧊', grant: { type: 'ammo', weapon: 'ice-gun', amount: 50 } },
  { item: 'ammo-hyper-gun', name: 'Munição Nuclear', desc: '5 tiros', cost: 10000, currency: 'money', icon: '☢️', grant: { type: 'ammo', weapon: 'hyper-gun', amount: 5 } },
  { item: 'ammo-void-blaster', name: 'Munição Estelar', desc: '25 tiros', cost: 7500, currency: 'money', icon: '🌟', grant: { type: 'ammo', weapon: 'void-blaster', amount: 25 } },
  { item: 'ammo-energy-cannon', name: 'Munição Gravitacional', desc: '10 tiros', cost: 5000, currency: 'money', icon: '🌀', grant: { type: 'ammo', weapon: 'energy-cannon', amount: 10 } },
  { item: 'ammo-heavy-crossbow', name: 'Munição Armadilha', desc: '25 tiros', cost: 1250, currency: 'money', icon: '🕸️', grant: { type: 'ammo', weapon: 'heavy-crossbow', amount: 25 } },
  { item: 'ammo-barrett', name: 'Munição Crítica', desc: '25 tiros', cost: 3000, currency: 'money', icon: '💀', grant: { type: 'ammo', weapon: 'barrett', amount: 25 } },
  { item: 'ammo-phantom-x', name: 'Munição Fantasma', desc: '25 tiros', cost: 4000, currency: 'money', icon: '👻', grant: { type: 'ammo', weapon: 'phantom-x', amount: 25 } },
  { item: 'ammo-vampire-x', name: 'Munição Vampírica', desc: '25 tiros', cost: 5000, currency: 'money', icon: '🩸', grant: { type: 'ammo', weapon: 'vampire-x', amount: 25 } },
  { item: 'ammo-plasma-shotgun', name: 'Munição Prisma', desc: '50 tiros', cost: 6000, currency: 'money', icon: '🌈', grant: { type: 'ammo', weapon: 'plasma-shotgun', amount: 50 } },
  { item: 'ammo-hyper-gun', name: 'Munição Suprema', desc: '100 tiros', cost: 15000, currency: 'money', icon: '🔱', grant: { type: 'ammo', weapon: 'hyper-gun', amount: 100 } }
    ]
  },
  {
    id: 'armors', icon: '🛡️', title: 'ARMADURAS COMPLETAS', currency: 'money',
    items: [
  { item: 'armor-full-couro-reforcado', name: 'Couro Reforçado', desc: '+25 HP · permanente', cost: 1500, currency: 'money', icon: '🟤', grant: { type: 'armorHp', hp: 25 } },
  { item: 'armor-full-couro-tatico', name: 'Couro Tático', desc: '+35 HP · permanente', cost: 1800, currency: 'money', icon: '🟤', grant: { type: 'armorHp', hp: 35 } },
  { item: 'armor-full-ouro-reforcado', name: 'Ouro Reforçado', desc: '+40 HP · permanente', cost: 3000, currency: 'money', icon: '🟡', grant: { type: 'armorHp', hp: 40 } },
  { item: 'armor-full-ouro-elite', name: 'Ouro Elite', desc: '+50 HP · permanente', cost: 4000, currency: 'money', icon: '🟡', grant: { type: 'armorHp', hp: 50 } },
  { item: 'armor-full-ferro-reforcado', name: 'Ferro Reforçado', desc: '+65 HP · permanente', cost: 6500, currency: 'money', icon: '⚪', grant: { type: 'armorHp', hp: 65 } },
  { item: 'armor-full-ferro-elite', name: 'Ferro Elite', desc: '+80 HP · permanente', cost: 8000, currency: 'money', icon: '⚪', grant: { type: 'armorHp', hp: 80 } },
  { item: 'armor-full-diamante-reforcado', name: 'Diamante Reforçado', desc: '+125 HP · permanente', cost: 13500, currency: 'money', icon: '💎', grant: { type: 'armorHp', hp: 125 } },
  { item: 'armor-full-diamante-elite', name: 'Diamante Elite', desc: '+150 HP · permanente', cost: 17500, currency: 'money', icon: '💎', grant: { type: 'armorHp', hp: 150 } },
  { item: 'armor-full-void-reforcada', name: 'Void Reforçada', desc: '+600 HP · permanente', cost: 65000, currency: 'money', icon: '🕳️', grant: { type: 'armorHp', hp: 600 } },
  { item: 'armor-full-void-elite', name: 'Void Elite', desc: '+750 HP · permanente', cost: 80000, currency: 'money', icon: '🕳️', grant: { type: 'armorHp', hp: 750 } },
  { item: 'armor-full-titanio', name: 'Titânio', desc: '+175 HP · permanente', cost: 20000, currency: 'money', icon: '🛡️', grant: { type: 'armorHp', hp: 175 } },
  { item: 'armor-full-titanio-elite', name: 'Titânio Elite', desc: '+225 HP · permanente', cost: 27500, currency: 'money', icon: '🛡️', grant: { type: 'armorHp', hp: 225 } },
  { item: 'armor-full-plasma', name: 'Plasma', desc: '+250 HP · permanente', cost: 30000, currency: 'money', icon: '⚡', grant: { type: 'armorHp', hp: 250 } },
  { item: 'armor-full-plasma-elite', name: 'Plasma Elite', desc: '+300 HP · permanente', cost: 40000, currency: 'money', icon: '⚡', grant: { type: 'armorHp', hp: 300 } },
  { item: 'armor-full-inferno', name: 'Inferno', desc: '+350 HP · permanente', cost: 45000, currency: 'money', icon: '🔥', grant: { type: 'armorHp', hp: 350 } },
  { item: 'armor-full-glacial', name: 'Glacial', desc: '+350 HP · permanente', cost: 45000, currency: 'money', icon: '❄️', grant: { type: 'armorHp', hp: 350 } },
  { item: 'armor-full-thunder', name: 'Thunder', desc: '+400 HP · permanente', cost: 50000, currency: 'money', icon: '⚡', grant: { type: 'armorHp', hp: 400 } },
  { item: 'armor-full-gravity', name: 'Gravity', desc: '+425 HP · permanente', cost: 55000, currency: 'money', icon: '🌀', grant: { type: 'armorHp', hp: 425 } },
  { item: 'armor-full-cosmic', name: 'Cosmic', desc: '+450 HP · permanente', cost: 60000, currency: 'money', icon: '🌌', grant: { type: 'armorHp', hp: 450 } },
  { item: 'armor-full-stellar', name: 'Stellar', desc: '+500 HP · permanente', cost: 65000, currency: 'money', icon: '🌟', grant: { type: 'armorHp', hp: 500 } },
  { item: 'armor-full-phantom', name: 'Phantom', desc: '+300 HP · permanente', cost: 40000, currency: 'money', icon: '👻', grant: { type: 'armorHp', hp: 300 } },
  { item: 'armor-full-reaper', name: 'Reaper', desc: '+400 HP · permanente', cost: 55000, currency: 'money', icon: '💀', grant: { type: 'armorHp', hp: 400 } },
  { item: 'armor-full-demon', name: 'Demon', desc: '+450 HP · permanente', cost: 60000, currency: 'money', icon: '😈', grant: { type: 'armorHp', hp: 450 } },
  { item: 'armor-full-angel', name: 'Angel', desc: '+450 HP · permanente', cost: 60000, currency: 'money', icon: '😇', grant: { type: 'armorHp', hp: 450 } },
  { item: 'armor-full-dragon', name: 'Dragon', desc: '+550 HP · permanente', cost: 70000, currency: 'money', icon: '🐉', grant: { type: 'armorHp', hp: 550 } },
  { item: 'armor-full-ancient-dragon', name: 'Ancient Dragon', desc: '+650 HP · permanente', cost: 85000, currency: 'money', icon: '🐉', grant: { type: 'armorHp', hp: 650 } },
  { item: 'armor-full-spider', name: 'Spider', desc: '+275 HP · permanente', cost: 35000, currency: 'money', icon: '🕸️', grant: { type: 'armorHp', hp: 275 } },
  { item: 'armor-full-scorpion', name: 'Scorpion', desc: '+325 HP · permanente', cost: 42500, currency: 'money', icon: '🦂', grant: { type: 'armorHp', hp: 325 } },
  { item: 'armor-full-cyber', name: 'Cyber', desc: '+375 HP · permanente', cost: 47500, currency: 'money', icon: '🦾', grant: { type: 'armorHp', hp: 375 } },
  { item: 'armor-full-robo', name: 'Robo', desc: '+425 HP · permanente', cost: 52500, currency: 'money', icon: '🤖', grant: { type: 'armorHp', hp: 425 } },
  { item: 'armor-full-mutant', name: 'Mutant', desc: '+500 HP · permanente', cost: 60000, currency: 'money', icon: '🧪', grant: { type: 'armorHp', hp: 500 } },
  { item: 'armor-full-dark', name: 'Dark', desc: '+550 HP · permanente', cost: 70000, currency: 'money', icon: '🌑', grant: { type: 'armorHp', hp: 550 } },
  { item: 'armor-full-solar', name: 'Solar', desc: '+600 HP · permanente', cost: 75000, currency: 'money', icon: '☀️', grant: { type: 'armorHp', hp: 600 } },
  { item: 'armor-full-lunar', name: 'Lunar', desc: '+600 HP · permanente', cost: 75000, currency: 'money', icon: '🌙', grant: { type: 'armorHp', hp: 600 } },
  { item: 'armor-full-prism', name: 'Prism', desc: '+650 HP · permanente', cost: 80000, currency: 'money', icon: '🌈', grant: { type: 'armorHp', hp: 650 } },
  { item: 'armor-full-crystal', name: 'Crystal', desc: '+700 HP · permanente', cost: 90000, currency: 'money', icon: '💠', grant: { type: 'armorHp', hp: 700 } },
  { item: 'armor-full-mystic', name: 'Mystic', desc: '+750 HP · permanente', cost: 100000, currency: 'money', icon: '🔮', grant: { type: 'armorHp', hp: 750 } },
  { item: 'armor-full-royal', name: 'Royal', desc: '+800 HP · permanente', cost: 110000, currency: 'money', icon: '👑', grant: { type: 'armorHp', hp: 800 } },
  { item: 'armor-full-champion', name: 'Champion', desc: '+850 HP · permanente', cost: 120000, currency: 'money', icon: '🏆', grant: { type: 'armorHp', hp: 850 } },
  { item: 'armor-full-warrior', name: 'Warrior', desc: '+900 HP · permanente', cost: 125000, currency: 'money', icon: '⚔️', grant: { type: 'armorHp', hp: 900 } },
  { item: 'armor-full-guardian', name: 'Guardian', desc: '+950 HP · permanente', cost: 135000, currency: 'money', icon: '🛡️', grant: { type: 'armorHp', hp: 950 } },
  { item: 'armor-full-titan', name: 'Titan', desc: '+1000 HP · permanente', cost: 150000, currency: 'money', icon: '🛡️', grant: { type: 'armorHp', hp: 1000 } },
  { item: 'armor-full-galaxy', name: 'Galaxy', desc: '+1100 HP · permanente', cost: 175000, currency: 'money', icon: '🌌', grant: { type: 'armorHp', hp: 1100 } },
  { item: 'armor-full-universe', name: 'Universe', desc: '+1250 HP · permanente', cost: 200000, currency: 'money', icon: '🌠', grant: { type: 'armorHp', hp: 1250 } },
  { item: 'armor-full-void-master', name: 'Void Master', desc: '+1500 HP · permanente', cost: 250000, currency: 'money', icon: '🕳️', grant: { type: 'armorHp', hp: 1500 } },
  { item: 'armor-full-void-god', name: 'Void God', desc: '+2000 HP · permanente', cost: 350000, currency: 'money', icon: '🕳️', grant: { type: 'armorHp', hp: 2000 } },
  { item: 'armor-full-meteor', name: 'Meteor', desc: '+1300 HP · permanente', cost: 225000, currency: 'money', icon: '☄️', grant: { type: 'armorHp', hp: 1300 } },
  { item: 'armor-full-infinity-armor', name: 'Infinity Armor', desc: '+1750 HP · permanente', cost: 300000, currency: 'money', icon: '💫', grant: { type: 'armorHp', hp: 1750 } },
  { item: 'armor-full-eternal', name: 'Eternal', desc: '+2500 HP · permanente', cost: 450000, currency: 'money', icon: '♾️', grant: { type: 'armorHp', hp: 2500 } },
  { item: 'armor-full-ultimate', name: 'Ultimate', desc: '+3000 HP · permanente', cost: 500000, currency: 'money', icon: '🌟', grant: { type: 'armorHp', hp: 3000 } }
    ]
  },
  {
    id: 'skills', icon: '💥', title: 'HABILIDADES', currency: 'tokens',
    items: [
{ item: 'skill-dash', name: 'Dash', desc: 'avanço rápido · CD 10s', cost: 3, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'skill_dash' } },
  { item: 'skill-dash-ii', name: 'Dash II', desc: 'avanço duplo · CD 15s', cost: 5, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'skill_dash_ii' } },
  { item: 'skill-escudo', name: 'Escudo', desc: '200 HP · CD 30s', cost: 5, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'skill_escudo' } },
  { item: 'skill-escudo-ii', name: 'Escudo II', desc: '500 HP · CD 45s', cost: 9, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'skill_escudo_ii' } },
  { item: 'skill-cura', name: 'Cura', desc: '+150 HP · CD 20s', cost: 4, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'skill_cura' } },
  { item: 'skill-cura-ii', name: 'Cura II', desc: '+300 HP · CD 30s', cost: 7, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'skill_cura_ii' } },
  { item: 'skill-explosao', name: 'Explosão', desc: 'AoE 100 · CD 20s', cost: 5, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'skill_explosao' } },
  { item: 'skill-mega-explosao', name: 'Mega Explosão', desc: 'AoE 350 · CD 40s', cost: 12, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'skill_mega_explosao' } },
  { item: 'skill-choque', name: 'Choque', desc: 'dano 150 · CD 15s', cost: 5, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'skill_choque' } },
  { item: 'skill-mega-choque', name: 'Mega Choque', desc: 'dano 400 · CD 30s', cost: 10, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'skill_mega_choque' } },
  { item: 'skill-congelar', name: 'Congelar', desc: 'paralisa 3s · CD 25s', cost: 7, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'skill_congelar' } },
  { item: 'skill-mega-congelar', name: 'Mega Congelar', desc: 'paralisa 6s · CD 40s', cost: 12, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'skill_mega_congelar' } },
  { item: 'skill-incendiar', name: 'Incendiar', desc: 'dano contínuo · CD 20s', cost: 6, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'skill_incendiar' } },
  { item: 'skill-inferno', name: 'Inferno', desc: 'AoE · CD 45s', cost: 13, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'skill_inferno' } },
  { item: 'skill-teleporte-ii', name: 'Teleporte II', desc: 'alcance aumentado · CD 10s', cost: 10, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'skill_teleporte_ii' } },
  { item: 'skill-teleporte-global', name: 'Teleporte Global', desc: 'CD 30s', cost: 15, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'skill_teleporte_global' } },
  { item: 'skill-invisibilidade', name: 'Invisibilidade', desc: '10s · CD 30s', cost: 10, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'skill_invisibilidade' } },
  { item: 'skill-invisibilidade-ii', name: 'Invisibilidade II', desc: '20s · CD 50s', cost: 15, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'skill_invisibilidade_ii' } },
  { item: 'skill-rush', name: 'Rush', desc: '+150% velocidade · 10s · CD 30s', cost: 8, currency: 'tokens', icon: '🏃', grant: { type: 'flag', key: 'skill_rush' } },
  { item: 'skill-mega-rush', name: 'Mega Rush', desc: '+300% velocidade · 10s · CD 45s', cost: 15, currency: 'tokens', icon: '🏃', grant: { type: 'flag', key: 'skill_mega_rush' } },
  { item: 'skill-mira-automatica', name: 'Mira Automática', desc: '10s · CD 30s', cost: 8, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'skill_mira_automatica' } },
  { item: 'skill-mira-suprema', name: 'Mira Suprema', desc: '20s · CD 45s', cost: 14, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'skill_mira_suprema' } },
  { item: 'skill-tiro-explosivo', name: 'Tiro Explosivo', desc: '5 tiros · CD 20s', cost: 7, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'skill_tiro_explosivo' } },
  { item: 'skill-tiro-eletrico', name: 'Tiro Elétrico', desc: '5 tiros · CD 20s', cost: 8, currency: 'tokens', icon: '🔫', grant: { type: 'flag', key: 'skill_tiro_eletrico' } },
  { item: 'skill-tiro-congelante', name: 'Tiro Congelante', desc: '5 tiros · CD 20s', cost: 8, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'skill_tiro_congelante' } },
  { item: 'skill-tiro-flamejante', name: 'Tiro Flamejante', desc: '5 tiros · CD 20s', cost: 8, currency: 'tokens', icon: '🔫', grant: { type: 'flag', key: 'skill_tiro_flamejante' } },
  { item: 'skill-tiro-void', name: 'Tiro Void', desc: '5 tiros · CD 30s', cost: 12, currency: 'tokens', icon: '🔫', grant: { type: 'flag', key: 'skill_tiro_void' } },
  { item: 'skill-ima', name: 'Ímã', desc: 'coleta automática · 30s · CD 30s', cost: 6, currency: 'tokens', icon: '🧲', grant: { type: 'flag', key: 'skill_ima' } },
  { item: 'skill-fortuna', name: 'Fortuna', desc: '+100% dinheiro · 60s · CD 60s', cost: 8, currency: 'tokens', icon: '🪙', grant: { type: 'flag', key: 'skill_fortuna' } },
  { item: 'skill-segunda-chance', name: 'Segunda Chance', desc: 'evita eliminação · CD 90s', cost: 15, currency: 'tokens', icon: '❤️', grant: { type: 'flag', key: 'skill_segunda_chance' } },
  { item: 'skill-invencivel', name: 'Invencível', desc: '5s · CD 45s', cost: 12, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'skill_invencivel' } },
  { item: 'skill-invencivel-ii', name: 'Invencível II', desc: '10s · CD 60s', cost: 20, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'skill_invencivel_ii' } },
  { item: 'skill-reaper', name: 'Reaper', desc: 'dano aumentado · 15s · CD 45s', cost: 14, currency: 'tokens', icon: '💀', grant: { type: 'flag', key: 'skill_reaper' } },
  { item: 'skill-rei-do-campo', name: 'Rei do Campo', desc: 'atributos +50% · 20s · CD 90s', cost: 20, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'skill_rei_do_campo' } },
  { item: 'skill-gravidade', name: 'Gravidade', desc: 'atrai inimigos · 10s · CD 45s', cost: 15, currency: 'tokens', icon: '🌌', grant: { type: 'flag', key: 'skill_gravidade' } },
  { item: 'skill-vortice', name: 'Vórtice', desc: 'puxa inimigos · 8s · CD 40s', cost: 13, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'skill_vortice' } },
  { item: 'skill-meteoro', name: 'Meteoro', desc: 'AoE 500 · CD 60s', cost: 18, currency: 'tokens', icon: '☄️', grant: { type: 'flag', key: 'skill_meteoro' } },
  { item: 'skill-tempestade', name: 'Tempestade', desc: 'dano contínuo · 15s · CD 60s', cost: 20, currency: 'tokens', icon: '🌩️', grant: { type: 'flag', key: 'skill_tempestade' } },
  { item: 'skill-vulcao', name: 'Vulcão', desc: 'AoE 600 · CD 75s', cost: 22, currency: 'tokens', icon: '🌋', grant: { type: 'flag', key: 'skill_vulcao' } },
  { item: 'skill-onda', name: 'Onda', desc: 'empurra inimigos · CD 30s', cost: 8, currency: 'tokens', icon: '🌊', grant: { type: 'flag', key: 'skill_onda' } },
  { item: 'skill-tornado', name: 'Tornado', desc: 'dano AoE · 10s · CD 50s', cost: 16, currency: 'tokens', icon: '🌪️', grant: { type: 'flag', key: 'skill_tornado' } },
  { item: 'skill-dark-pulse', name: 'Dark Pulse', desc: 'dano 500 · CD 40s', cost: 15, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'skill_dark_pulse' } },
  { item: 'skill-star-burst', name: 'Star Burst', desc: 'dano 750 · CD 60s', cost: 22, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'skill_star_burst' } },
  { item: 'skill-infinity', name: 'Infinity', desc: 'todos os efeitos · 10s · CD 90s', cost: 30, currency: 'tokens', icon: '♾️', grant: { type: 'flag', key: 'skill_infinity' } },
  { item: 'skill-tridente', name: 'Tridente', desc: 'ataque especial · CD 45s', cost: 18, currency: 'tokens', icon: '🔱', grant: { type: 'flag', key: 'skill_tridente' } },
  { item: 'skill-dragon-breath', name: 'Dragon Breath', desc: 'AoE 800 · CD 60s', cost: 25, currency: 'tokens', icon: '🐉', grant: { type: 'flag', key: 'skill_dragon_breath' } },
  { item: 'skill-royal-blast', name: 'Royal Blast', desc: 'dano 1.000 · CD 90s', cost: 30, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'skill_royal_blast' } },
  { item: 'skill-void-blast', name: 'Void Blast', desc: 'dano 1.500 · CD 90s', cost: 35, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'skill_void_blast' } },
  { item: 'skill-cosmic-ray', name: 'Cosmic Ray', desc: 'dano 2.000 · CD 120s', cost: 40, currency: 'tokens', icon: '💫', grant: { type: 'flag', key: 'skill_cosmic_ray' } },
  { item: 'skill-ultimate', name: 'Ultimate', desc: 'habilidade suprema · CD 180s', cost: 50, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'skill_ultimate' } },
    ]
  },
  {
    id: 'enchants', icon: '🪄', title: 'ENCANTAMENTOS', currency: 'tokens',
    items: [
{ item: 'enchant2-fogo-ii', name: 'Fogo II', desc: 'dano flamejante', cost: 15, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'enchant2_fogo_ii' } },
  { item: 'enchant2-inferno', name: 'Inferno', desc: 'fogo intenso', cost: 25, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'enchant2_inferno' } },
  { item: 'enchant2-gelado-ii', name: 'Gelado II', desc: 'lentidão 7s', cost: 15, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'enchant2_gelado_ii' } },
  { item: 'enchant2-congelante', name: 'Congelante', desc: 'lentidão 10s', cost: 20, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'enchant2_congelante' } },
  { item: 'enchant2-raio-ii', name: 'Raio II', desc: 'eletricidade intensa', cost: 20, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'enchant2_raio_ii' } },
  { item: 'enchant2-tempestade', name: 'Tempestade', desc: 'efeito elétrico', cost: 30, currency: 'tokens', icon: '🌩️', grant: { type: 'flag', key: 'enchant2_tempestade' } },
  { item: 'enchant2-vampirico', name: 'Vampírico', desc: 'recupera HP ao dar dano', cost: 25, currency: 'tokens', icon: '🩸', grant: { type: 'flag', key: 'enchant2_vampirico' } },
  { item: 'enchant2-vampirico-ii', name: 'Vampírico II', desc: 'recuperação aumentada', cost: 40, currency: 'tokens', icon: '🩸', grant: { type: 'flag', key: 'enchant2_vampirico_ii' } },
  { item: 'enchant2-void', name: 'Void', desc: 'energia Void', cost: 35, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'enchant2_void' } },
  { item: 'enchant2-void-ii', name: 'Void II', desc: 'energia Void intensa', cost: 50, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'enchant2_void_ii' } },
  { item: 'enchant2-brilhante', name: 'Brilhante', desc: 'brilho especial', cost: 8, currency: 'tokens', icon: '✨', grant: { type: 'flag', key: 'enchant2_brilhante' } },
  { item: 'enchant2-prisma', name: 'Prisma', desc: 'efeito colorido', cost: 18, currency: 'tokens', icon: '🌈', grant: { type: 'flag', key: 'enchant2_prisma' } },
  { item: 'enchant2-sombrio', name: 'Sombrio', desc: 'aura escura', cost: 15, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'enchant2_sombrio' } },
  { item: 'enchant2-solar', name: 'Solar', desc: 'aura solar', cost: 20, currency: 'tokens', icon: '☀️', grant: { type: 'flag', key: 'enchant2_solar' } },
  { item: 'enchant2-lunar', name: 'Lunar', desc: 'aura lunar', cost: 20, currency: 'tokens', icon: '🌙', grant: { type: 'flag', key: 'enchant2_lunar' } },
  { item: 'enchant2-vento', name: 'Vento', desc: 'partículas de vento', cost: 12, currency: 'tokens', icon: '💨', grant: { type: 'flag', key: 'enchant2_vento' } },
  { item: 'enchant2-tornado', name: 'Tornado', desc: 'efeito de vento', cost: 25, currency: 'tokens', icon: '🌪️', grant: { type: 'flag', key: 'enchant2_tornado' } },
  { item: 'enchant2-agua', name: 'Água', desc: 'efeito aquático', cost: 12, currency: 'tokens', icon: '🌊', grant: { type: 'flag', key: 'enchant2_agua' } },
  { item: 'enchant2-lava', name: 'Lava', desc: 'efeito de lava', cost: 30, currency: 'tokens', icon: '🌋', grant: { type: 'flag', key: 'enchant2_lava' } },
  { item: 'enchant2-meteoro', name: 'Meteoro', desc: 'partículas de meteoro', cost: 35, currency: 'tokens', icon: '☄️', grant: { type: 'flag', key: 'enchant2_meteoro' } },
  { item: 'enchant2-cristal', name: 'Cristal', desc: 'efeito cristalino', cost: 25, currency: 'tokens', icon: '💎', grant: { type: 'flag', key: 'enchant2_cristal' } },
  { item: 'enchant2-mistico', name: 'Místico', desc: 'aura mística', cost: 30, currency: 'tokens', icon: '🔮', grant: { type: 'flag', key: 'enchant2_mistico' } },
  { item: 'enchant2-fantasma', name: 'Fantasma', desc: 'partículas fantasma', cost: 25, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'enchant2_fantasma' } },
  { item: 'enchant2-aranha', name: 'Aranha', desc: 'efeito de teia', cost: 20, currency: 'tokens', icon: '🕸️', grant: { type: 'flag', key: 'enchant2_aranha' } },
  { item: 'enchant2-explosivo', name: 'Explosivo', desc: 'impacto visual', cost: 20, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'enchant2_explosivo' } },
  { item: 'enchant2-precisao', name: 'Precisão', desc: 'efeito de mira', cost: 15, currency: 'tokens', icon: '🎯', grant: { type: 'flag', key: 'enchant2_precisao' } },
  { item: 'enchant2-guerreiro', name: 'Guerreiro', desc: 'aura de combate', cost: 20, currency: 'tokens', icon: '⚔️', grant: { type: 'flag', key: 'enchant2_guerreiro' } },
  { item: 'enchant2-guardiao', name: 'Guardião', desc: 'aura defensiva', cost: 25, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'enchant2_guardiao' } },
  { item: 'enchant2-real', name: 'Real', desc: 'aura dourada', cost: 35, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'enchant2_real' } },
  { item: 'enchant2-dragao', name: 'Dragão', desc: 'partículas de dragão', cost: 40, currency: 'tokens', icon: '🐉', grant: { type: 'flag', key: 'enchant2_dragao' } },
  { item: 'enchant2-dragao-negro', name: 'Dragão Negro', desc: 'aura negra', cost: 50, currency: 'tokens', icon: '🐉', grant: { type: 'flag', key: 'enchant2_dragao_negro' } },
  { item: 'enchant2-anjo', name: 'Anjo', desc: 'partículas angelicais', cost: 35, currency: 'tokens', icon: '😇', grant: { type: 'flag', key: 'enchant2_anjo' } },
  { item: 'enchant2-demonio', name: 'Demônio', desc: 'aura demoníaca', cost: 35, currency: 'tokens', icon: '😈', grant: { type: 'flag', key: 'enchant2_demonio' } },
  { item: 'enchant2-cosmico', name: 'Cósmico', desc: 'partículas cósmicas', cost: 45, currency: 'tokens', icon: '💫', grant: { type: 'flag', key: 'enchant2_cosmico' } },
  { item: 'enchant2-galaxia', name: 'Galáxia', desc: 'efeito galáctico', cost: 50, currency: 'tokens', icon: '🌌', grant: { type: 'flag', key: 'enchant2_galaxia' } },
  { item: 'enchant2-infinito', name: 'Infinito', desc: 'aura infinita', cost: 60, currency: 'tokens', icon: '♾️', grant: { type: 'flag', key: 'enchant2_infinito' } },
  { item: 'enchant2-estelar', name: 'Estelar', desc: 'partículas estelares', cost: 40, currency: 'tokens', icon: '🌠', grant: { type: 'flag', key: 'enchant2_estelar' } },
  { item: 'enchant2-plasma', name: 'Plasma', desc: 'efeito energético', cost: 35, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'enchant2_plasma' } },
  { item: 'enchant2-energia', name: 'Energia', desc: 'aura energética', cost: 25, currency: 'tokens', icon: '🔋', grant: { type: 'flag', key: 'enchant2_energia' } },
  { item: 'enchant2-gravidade', name: 'Gravidade', desc: 'distorção visual', cost: 45, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'enchant2_gravidade' } },
  { item: 'enchant2-glacial', name: 'Glacial', desc: 'aura congelada', cost: 30, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'enchant2_glacial' } },
  { item: 'enchant2-infernal', name: 'Infernal', desc: 'aura de fogo', cost: 45, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'enchant2_infernal' } },
  { item: 'enchant2-eclipse', name: 'Eclipse', desc: 'aura de eclipse', cost: 50, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'enchant2_eclipse' } },
  { item: 'enchant2-supernova', name: 'Supernova', desc: 'efeito solar', cost: 55, currency: 'tokens', icon: '☀️', grant: { type: 'flag', key: 'enchant2_supernova' } },
  { item: 'enchant2-cometa', name: 'Cometa', desc: 'partículas rápidas', cost: 35, currency: 'tokens', icon: '☄️', grant: { type: 'flag', key: 'enchant2_cometa' } },
  { item: 'enchant2-diamante', name: 'Diamante', desc: 'brilho cristalino', cost: 40, currency: 'tokens', icon: '💠', grant: { type: 'flag', key: 'enchant2_diamante' } },
  { item: 'enchant2-planetario', name: 'Planetário', desc: 'partículas orbitais', cost: 50, currency: 'tokens', icon: '🪐', grant: { type: 'flag', key: 'enchant2_planetario' } },
  { item: 'enchant2-universal', name: 'Universal', desc: 'efeito espacial', cost: 60, currency: 'tokens', icon: '🌌', grant: { type: 'flag', key: 'enchant2_universal' } },
  { item: 'enchant2-void-supremo', name: 'Void Supremo', desc: 'aura Void intensa', cost: 75, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'enchant2_void_supremo' } },
  { item: 'enchant2-divino', name: 'Divino', desc: 'efeito lendário', cost: 100, currency: 'tokens', icon: '✨', grant: { type: 'flag', key: 'enchant2_divino' } },
    ]
  },
  {
    id: 'skins', icon: '👤', title: 'SKINS DE JOGADOR', currency: 'tokens',
    items: [
{ item: 'skin2-toxic', name: 'Toxic', desc: 'estilo tóxico', cost: 20, currency: 'tokens', icon: '🟢', grant: { type: 'flag', key: 'skin2_toxic' } },
  { item: 'skin2-ocean', name: 'Ocean', desc: 'estilo oceano', cost: 20, currency: 'tokens', icon: '🔵', grant: { type: 'flag', key: 'skin2_ocean' } },
  { item: 'skin2-galaxy', name: 'Galaxy', desc: 'estilo galáxia', cost: 35, currency: 'tokens', icon: '🟣', grant: { type: 'flag', key: 'skin2_galaxy' } },
  { item: 'skin2-gold', name: 'Gold', desc: 'estilo dourado', cost: 35, currency: 'tokens', icon: '🟡', grant: { type: 'flag', key: 'skin2_gold' } },
  { item: 'skin2-snow', name: 'Snow', desc: 'estilo neve', cost: 25, currency: 'tokens', icon: '⚪', grant: { type: 'flag', key: 'skin2_snow' } },
  { item: 'skin2-inferno-skin', name: 'Inferno Skin', desc: 'estilo infernal', cost: 40, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'skin2_inferno_skin' } },
  { item: 'skin2-ice-skin', name: 'Ice Skin', desc: 'estilo gelo', cost: 40, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'skin2_ice_skin' } },
  { item: 'skin2-thunder-skin', name: 'Thunder Skin', desc: 'estilo elétrico', cost: 45, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'skin2_thunder_skin' } },
  { item: 'skin2-dark-skin', name: 'Dark Skin', desc: 'estilo sombrio', cost: 35, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'skin2_dark_skin' } },
  { item: 'skin2-star-skin', name: 'Star Skin', desc: 'estilo estelar', cost: 45, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'skin2_star_skin' } },
  { item: 'skin2-rainbow', name: 'Rainbow', desc: 'estilo arco-íris', cost: 50, currency: 'tokens', icon: '🌈', grant: { type: 'flag', key: 'skin2_rainbow' } },
  { item: 'skin2-spider-skin', name: 'Spider Skin', desc: 'estilo aranha', cost: 35, currency: 'tokens', icon: '🕸️', grant: { type: 'flag', key: 'skin2_spider_skin' } },
  { item: 'skin2-ghost-skin', name: 'Ghost Skin', desc: 'estilo fantasma', cost: 40, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'skin2_ghost_skin' } },
  { item: 'skin2-reaper-skin', name: 'Reaper Skin', desc: 'estilo ceifador', cost: 50, currency: 'tokens', icon: '💀', grant: { type: 'flag', key: 'skin2_reaper_skin' } },
  { item: 'skin2-demon-skin', name: 'Demon Skin', desc: 'estilo demônio', cost: 55, currency: 'tokens', icon: '😈', grant: { type: 'flag', key: 'skin2_demon_skin' } },
  { item: 'skin2-angel-skin', name: 'Angel Skin', desc: 'estilo anjo', cost: 55, currency: 'tokens', icon: '😇', grant: { type: 'flag', key: 'skin2_angel_skin' } },
  { item: 'skin2-dragon-skin', name: 'Dragon Skin', desc: 'estilo dragão', cost: 60, currency: 'tokens', icon: '🐉', grant: { type: 'flag', key: 'skin2_dragon_skin' } },
  { item: 'skin2-dragon-black', name: 'Dragon Black', desc: 'dragão negro', cost: 75, currency: 'tokens', icon: '🐲', grant: { type: 'flag', key: 'skin2_dragon_black' } },
  { item: 'skin2-robot', name: 'Robot', desc: 'estilo robótico', cost: 45, currency: 'tokens', icon: '🤖', grant: { type: 'flag', key: 'skin2_robot' } },
  { item: 'skin2-cyber-skin', name: 'Cyber Skin', desc: 'estilo cyber', cost: 50, currency: 'tokens', icon: '🦾', grant: { type: 'flag', key: 'skin2_cyber_skin' } },
  { item: 'skin2-mutant-skin', name: 'Mutant Skin', desc: 'estilo mutante', cost: 45, currency: 'tokens', icon: '🧪', grant: { type: 'flag', key: 'skin2_mutant_skin' } },
  { item: 'skin2-knight', name: 'Knight', desc: 'estilo cavaleiro', cost: 40, currency: 'tokens', icon: '🛡️', grant: { type: 'flag', key: 'skin2_knight' } },
  { item: 'skin2-warrior-skin', name: 'Warrior Skin', desc: 'estilo guerreiro', cost: 45, currency: 'tokens', icon: '⚔️', grant: { type: 'flag', key: 'skin2_warrior_skin' } },
  { item: 'skin2-king', name: 'King', desc: 'estilo rei', cost: 60, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'skin2_king' } },
  { item: 'skin2-queen', name: 'Queen', desc: 'estilo rainha', cost: 60, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'skin2_queen' } },
  { item: 'skin2-champion-skin', name: 'Champion Skin', desc: 'estilo campeão', cost: 65, currency: 'tokens', icon: '🏆', grant: { type: 'flag', key: 'skin2_champion_skin' } },
  { item: 'skin2-diamond-skin', name: 'Diamond Skin', desc: 'estilo diamante', cost: 70, currency: 'tokens', icon: '💎', grant: { type: 'flag', key: 'skin2_diamond_skin' } },
  { item: 'skin2-void-master-skin', name: 'Void Master Skin', desc: 'Void avançado', cost: 80, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'skin2_void_master_skin' } },
  { item: 'skin2-cosmic-skin', name: 'Cosmic Skin', desc: 'estilo cósmico', cost: 75, currency: 'tokens', icon: '🌌', grant: { type: 'flag', key: 'skin2_cosmic_skin' } },
  { item: 'skin2-meteor-skin', name: 'Meteor Skin', desc: 'estilo meteoro', cost: 55, currency: 'tokens', icon: '☄️', grant: { type: 'flag', key: 'skin2_meteor_skin' } },
  { item: 'skin2-lunar-skin', name: 'Lunar Skin', desc: 'estilo lunar', cost: 45, currency: 'tokens', icon: '🌙', grant: { type: 'flag', key: 'skin2_lunar_skin' } },
  { item: 'skin2-solar-skin', name: 'Solar Skin', desc: 'estilo solar', cost: 45, currency: 'tokens', icon: '☀️', grant: { type: 'flag', key: 'skin2_solar_skin' } },
  { item: 'skin2-aqua', name: 'Aqua', desc: 'estilo aquático', cost: 30, currency: 'tokens', icon: '🌊', grant: { type: 'flag', key: 'skin2_aqua' } },
  { item: 'skin2-wind', name: 'Wind', desc: 'estilo vento', cost: 30, currency: 'tokens', icon: '🌪️', grant: { type: 'flag', key: 'skin2_wind' } },
  { item: 'skin2-lava-skin', name: 'Lava Skin', desc: 'estilo lava', cost: 50, currency: 'tokens', icon: '🌋', grant: { type: 'flag', key: 'skin2_lava_skin' } },
  { item: 'skin2-glacier', name: 'Glacier', desc: 'estilo glacial', cost: 50, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'skin2_glacier' } },
  { item: 'skin2-mystic-skin', name: 'Mystic Skin', desc: 'estilo místico', cost: 65, currency: 'tokens', icon: '🔮', grant: { type: 'flag', key: 'skin2_mystic_skin' } },
  { item: 'skin2-starfall', name: 'Starfall', desc: 'estilo estrelas', cost: 70, currency: 'tokens', icon: '💫', grant: { type: 'flag', key: 'skin2_starfall' } },
  { item: 'skin2-planet', name: 'Planet', desc: 'estilo planetário', cost: 70, currency: 'tokens', icon: '🪐', grant: { type: 'flag', key: 'skin2_planet' } },
  { item: 'skin2-comet', name: 'Comet', desc: 'estilo cometa', cost: 65, currency: 'tokens', icon: '🌠', grant: { type: 'flag', key: 'skin2_comet' } },
  { item: 'skin2-infinity-skin', name: 'Infinity Skin', desc: 'estilo infinito', cost: 100, currency: 'tokens', icon: '♾️', grant: { type: 'flag', key: 'skin2_infinity_skin' } },
  { item: 'skin2-divine-skin', name: 'Divine Skin', desc: 'estilo divino', cost: 100, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'skin2_divine_skin' } },
  { item: 'skin2-void-god-skin', name: 'Void God Skin', desc: 'Void supremo', cost: 150, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'skin2_void_god_skin' } },
  { item: 'skin2-alien', name: 'Alien', desc: 'estilo alienígena', cost: 45, currency: 'tokens', icon: '👾', grant: { type: 'flag', key: 'skin2_alien' } },
  { item: 'skin2-vampire', name: 'Vampire', desc: 'estilo vampiro', cost: 55, currency: 'tokens', icon: '🧛', grant: { type: 'flag', key: 'skin2_vampire' } },
  { item: 'skin2-zombie', name: 'Zombie', desc: 'estilo zumbi', cost: 40, currency: 'tokens', icon: '🧟', grant: { type: 'flag', key: 'skin2_zombie' } },
  { item: 'skin2-ninja', name: 'Ninja', desc: 'estilo ninja', cost: 50, currency: 'tokens', icon: '🥷', grant: { type: 'flag', key: 'skin2_ninja' } },
  { item: 'skin2-cowboy', name: 'Cowboy', desc: 'estilo cowboy', cost: 35, currency: 'tokens', icon: '🤠', grant: { type: 'flag', key: 'skin2_cowboy' } },
  { item: 'skin2-pirate', name: 'Pirate', desc: 'estilo pirata', cost: 45, currency: 'tokens', icon: '🏴‍☠️', grant: { type: 'flag', key: 'skin2_pirate' } },
  { item: 'skin2-legend', name: 'Legend', desc: 'estilo lendário', cost: 200, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'skin2_legend' } },

    ]
  },
  {
    id: 'wskins', icon: '🎨', title: 'SKINS DE ARMAS', currency: 'tokens',
    items: [
{ item: 'wskin2-ouro-skin', name: 'Ouro Skin', desc: 'visual dourado', cost: 30, currency: 'tokens', icon: '🟡', grant: { type: 'flag', key: 'wskin2_ouro_skin' } },
  { item: 'wskin2-diamante-skin', name: 'Diamante Skin', desc: 'visual cristalino', cost: 40, currency: 'tokens', icon: '💎', grant: { type: 'flag', key: 'wskin2_diamante_skin' } },
  { item: 'wskin2-void-skin', name: 'Void Skin', desc: 'visual Void', cost: 50, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'wskin2_void_skin' } },
  { item: 'wskin2-flame-skin', name: 'Flame Skin', desc: 'visual flamejante', cost: 45, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'wskin2_flame_skin' } },
  { item: 'wskin2-ice-weapon', name: 'Ice Weapon', desc: 'visual congelado', cost: 40, currency: 'tokens', icon: '❄️', grant: { type: 'flag', key: 'wskin2_ice_weapon' } },
  { item: 'wskin2-thunder-weapon', name: 'Thunder Weapon', desc: 'visual elétrico', cost: 50, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'wskin2_thunder_weapon' } },
  { item: 'wskin2-rainbow-weapon', name: 'Rainbow Weapon', desc: 'visual colorido', cost: 55, currency: 'tokens', icon: '🌈', grant: { type: 'flag', key: 'wskin2_rainbow_weapon' } },
  { item: 'wskin2-dark-weapon', name: 'Dark Weapon', desc: 'visual sombrio', cost: 35, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'wskin2_dark_weapon' } },
  { item: 'wskin2-ghost-weapon', name: 'Ghost Weapon', desc: 'visual fantasma', cost: 45, currency: 'tokens', icon: '👻', grant: { type: 'flag', key: 'wskin2_ghost_weapon' } },
  { item: 'wskin2-reaper-weapon', name: 'Reaper Weapon', desc: 'visual ceifador', cost: 55, currency: 'tokens', icon: '💀', grant: { type: 'flag', key: 'wskin2_reaper_weapon' } },
  { item: 'wskin2-star-weapon', name: 'Star Weapon', desc: 'visual estelar', cost: 50, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'wskin2_star_weapon' } },
  { item: 'wskin2-galaxy-weapon', name: 'Galaxy Weapon', desc: 'visual galáctico', cost: 65, currency: 'tokens', icon: '🌌', grant: { type: 'flag', key: 'wskin2_galaxy_weapon' } },
  { item: 'wskin2-solar-weapon', name: 'Solar Weapon', desc: 'visual solar', cost: 55, currency: 'tokens', icon: '☀️', grant: { type: 'flag', key: 'wskin2_solar_weapon' } },
  { item: 'wskin2-lunar-weapon', name: 'Lunar Weapon', desc: 'visual lunar', cost: 55, currency: 'tokens', icon: '🌙', grant: { type: 'flag', key: 'wskin2_lunar_weapon' } },
  { item: 'wskin2-dragon-weapon', name: 'Dragon Weapon', desc: 'visual dragão', cost: 70, currency: 'tokens', icon: '🐉', grant: { type: 'flag', key: 'wskin2_dragon_weapon' } },
  { item: 'wskin2-dragon-black-weapon', name: 'Dragon Black Weapon', desc: 'dragão negro', cost: 90, currency: 'tokens', icon: '🐲', grant: { type: 'flag', key: 'wskin2_dragon_black_weapon' } },
  { item: 'wskin2-glacier-weapon', name: 'Glacier Weapon', desc: 'visual glacial', cost: 50, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'wskin2_glacier_weapon' } },
  { item: 'wskin2-lava-weapon', name: 'Lava Weapon', desc: 'visual lava', cost: 60, currency: 'tokens', icon: '🌋', grant: { type: 'flag', key: 'wskin2_lava_weapon' } },
  { item: 'wskin2-gravity-weapon', name: 'Gravity Weapon', desc: 'visual gravitacional', cost: 75, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'wskin2_gravity_weapon' } },
  { item: 'wskin2-mystic-weapon', name: 'Mystic Weapon', desc: 'visual místico', cost: 65, currency: 'tokens', icon: '🔮', grant: { type: 'flag', key: 'wskin2_mystic_weapon' } },
  { item: 'wskin2-toxic-weapon', name: 'Toxic Weapon', desc: 'visual tóxico', cost: 45, currency: 'tokens', icon: '🧪', grant: { type: 'flag', key: 'wskin2_toxic_weapon' } },
  { item: 'wskin2-spider-weapon', name: 'Spider Weapon', desc: 'visual aranha', cost: 35, currency: 'tokens', icon: '🕸️', grant: { type: 'flag', key: 'wskin2_spider_weapon' } },
  { item: 'wskin2-plasma-weapon', name: 'Plasma Weapon', desc: 'visual plasma', cost: 70, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'wskin2_plasma_weapon' } },
  { item: 'wskin2-cyber-weapon', name: 'Cyber Weapon', desc: 'visual cyber', cost: 60, currency: 'tokens', icon: '🤖', grant: { type: 'flag', key: 'wskin2_cyber_weapon' } },
  { item: 'wskin2-champion-weapon', name: 'Champion Weapon', desc: 'visual campeão', cost: 75, currency: 'tokens', icon: '🏆', grant: { type: 'flag', key: 'wskin2_champion_weapon' } },
  { item: 'wskin2-royal-weapon', name: 'Royal Weapon', desc: 'visual real', cost: 80, currency: 'tokens', icon: '👑', grant: { type: 'flag', key: 'wskin2_royal_weapon' } },
  { item: 'wskin2-divine-weapon', name: 'Divine Weapon', desc: 'visual divino', cost: 100, currency: 'tokens', icon: '✨', grant: { type: 'flag', key: 'wskin2_divine_weapon' } },
  { item: 'wskin2-infinity-weapon', name: 'Infinity Weapon', desc: 'visual infinito', cost: 120, currency: 'tokens', icon: '♾️', grant: { type: 'flag', key: 'wskin2_infinity_weapon' } },
  { item: 'wskin2-meteor-weapon', name: 'Meteor Weapon', desc: 'visual meteoro', cost: 70, currency: 'tokens', icon: '☄️', grant: { type: 'flag', key: 'wskin2_meteor_weapon' } },
  { item: 'wskin2-comet-weapon', name: 'Comet Weapon', desc: 'visual cometa', cost: 65, currency: 'tokens', icon: '🌠', grant: { type: 'flag', key: 'wskin2_comet_weapon' } },
  { item: 'wskin2-crystal-weapon', name: 'Crystal Weapon', desc: 'visual cristal', cost: 55, currency: 'tokens', icon: '💠', grant: { type: 'flag', key: 'wskin2_crystal_weapon' } },
  { item: 'wskin2-aqua-weapon', name: 'Aqua Weapon', desc: 'visual água', cost: 35, currency: 'tokens', icon: '🌊', grant: { type: 'flag', key: 'wskin2_aqua_weapon' } },
  { item: 'wskin2-wind-weapon', name: 'Wind Weapon', desc: 'visual vento', cost: 35, currency: 'tokens', icon: '🌪️', grant: { type: 'flag', key: 'wskin2_wind_weapon' } },
  { item: 'wskin2-stellar-weapon', name: 'Stellar Weapon', desc: 'visual estelar', cost: 75, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'wskin2_stellar_weapon' } },
  { item: 'wskin2-void-energy', name: 'Void Energy', desc: 'energia Void', cost: 90, currency: 'tokens', icon: '🕳️', grant: { type: 'flag', key: 'wskin2_void_energy' } },
  { item: 'wskin2-inferno-weapon', name: 'Inferno Weapon', desc: 'visual infernal', cost: 80, currency: 'tokens', icon: '🔥', grant: { type: 'flag', key: 'wskin2_inferno_weapon' } },
  { item: 'wskin2-frost-weapon', name: 'Frost Weapon', desc: 'visual congelante', cost: 70, currency: 'tokens', icon: '🧊', grant: { type: 'flag', key: 'wskin2_frost_weapon' } },
  { item: 'wskin2-lightning-weapon', name: 'Lightning Weapon', desc: 'visual raio', cost: 80, currency: 'tokens', icon: '⚡', grant: { type: 'flag', key: 'wskin2_lightning_weapon' } },
  { item: 'wskin2-explosive-weapon', name: 'Explosive Weapon', desc: 'visual explosivo', cost: 65, currency: 'tokens', icon: '💥', grant: { type: 'flag', key: 'wskin2_explosive_weapon' } },
  { item: 'wskin2-magnetic-weapon', name: 'Magnetic Weapon', desc: 'visual magnético', cost: 60, currency: 'tokens', icon: '🧲', grant: { type: 'flag', key: 'wskin2_magnetic_weapon' } },
  { item: 'wskin2-vortex-weapon', name: 'Vortex Weapon', desc: 'visual vórtice', cost: 75, currency: 'tokens', icon: '🌀', grant: { type: 'flag', key: 'wskin2_vortex_weapon' } },
  { item: 'wskin2-cosmic-weapon', name: 'Cosmic Weapon', desc: 'visual cósmico', cost: 90, currency: 'tokens', icon: '🪐', grant: { type: 'flag', key: 'wskin2_cosmic_weapon' } },
  { item: 'wskin2-eclipse-weapon', name: 'Eclipse Weapon', desc: 'visual eclipse', cost: 85, currency: 'tokens', icon: '🌑', grant: { type: 'flag', key: 'wskin2_eclipse_weapon' } },
  { item: 'wskin2-prism-weapon', name: 'Prism Weapon', desc: 'visual prisma', cost: 80, currency: 'tokens', icon: '🌈', grant: { type: 'flag', key: 'wskin2_prism_weapon' } },
  { item: 'wskin2-crimson', name: 'Crimson', desc: 'vermelho intenso', cost: 50, currency: 'tokens', icon: '🩸', grant: { type: 'flag', key: 'wskin2_crimson' } },
  { item: 'wskin2-emerald', name: 'Emerald', desc: 'visual esmeralda', cost: 55, currency: 'tokens', icon: '🟢', grant: { type: 'flag', key: 'wskin2_emerald' } },
  { item: 'wskin2-sapphire', name: 'Sapphire', desc: 'visual safira', cost: 55, currency: 'tokens', icon: '🔵', grant: { type: 'flag', key: 'wskin2_sapphire' } },
  { item: 'wskin2-amethyst', name: 'Amethyst', desc: 'visual ametista', cost: 55, currency: 'tokens', icon: '🟣', grant: { type: 'flag', key: 'wskin2_amethyst' } },
  { item: 'wskin2-obsidian', name: 'Obsidian', desc: 'visual obsidiana', cost: 70, currency: 'tokens', icon: '🖤', grant: { type: 'flag', key: 'wskin2_obsidian' } },
  { item: 'wskin2-ultimate-weapon', name: 'Ultimate Weapon', desc: 'visual lendário', cost: 150, currency: 'tokens', icon: '🌟', grant: { type: 'flag', key: 'wskin2_ultimate_weapon' } },
    ]
  },
  {
    id: 'revives', icon: '❤️', title: 'REVIVES', currency: 'money',
    items: [
{ item: 'revive2-revive-basico', name: 'Revive Básico', desc: 'reaparece uma vez', cost: 5750, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-rapido', name: 'Revive Rápido', desc: 'reaparece instantâneo', cost: 7500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-seguro', name: 'Revive Seguro', desc: 'reaparece com 50% HP', cost: 8000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-forte', name: 'Revive Forte', desc: 'reaparece com 100% HP', cost: 10000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-blindado', name: 'Revive Blindado', desc: 'reaparece com escudo', cost: 12500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-void', name: 'Revive Void', desc: 'reaparece com 500 HP', cost: 20000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-duplo', name: 'Revive Duplo', desc: '2 usos', cost: 15000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 2 } },
  { item: 'revive2-revive-triplo', name: 'Revive Triplo', desc: '3 usos', cost: 22500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 3 } },
  { item: 'revive2-revive-elite', name: 'Revive Elite', desc: 'reaparece com +100 HP', cost: 15000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-supremo', name: 'Revive Supremo', desc: 'reaparece com +250 HP', cost: 25000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-instantaneo', name: 'Revive Instantâneo', desc: 'sem atraso', cost: 18000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-protegido', name: 'Revive Protegido', desc: 'invulnerabilidade breve', cost: 20000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-ouro', name: 'Revive Ouro', desc: 'bônus de dinheiro', cost: 17500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-diamante', name: 'Revive Diamante', desc: 'reaparece com escudo', cost: 30000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-void-x', name: 'Revive Void X', desc: 'efeito Void', cost: 35000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-angel', name: 'Revive Angel', desc: 'efeito angelical', cost: 40000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-reaper', name: 'Revive Reaper', desc: 'efeito sombrio', cost: 40000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-dragon', name: 'Revive Dragon', desc: 'efeito dragão', cost: 45000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-cosmic', name: 'Revive Cosmic', desc: 'efeito cósmico', cost: 50000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-infinity-x', name: 'Revive Infinity X', desc: 'efeito especial', cost: 75000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-economico', name: 'Revive Econômico', desc: 'preço reduzido', cost: 4500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-premium', name: 'Revive Premium', desc: 'versão premium', cost: 12000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-tatico', name: 'Revive Tático', desc: 'local seguro', cost: 14000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-emergencia', name: 'Revive Emergência', desc: 'ativação automática', cost: 16000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-guardiao', name: 'Revive Guardião', desc: 'escudo ao reaparecer', cost: 20000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-flame', name: 'Revive Flame', desc: 'efeito de fogo', cost: 25000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-ice', name: 'Revive Ice', desc: 'efeito de gelo', cost: 25000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-thunder', name: 'Revive Thunder', desc: 'efeito elétrico', cost: 28000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-ghost', name: 'Revive Ghost', desc: 'efeito fantasma', cost: 30000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-dark', name: 'Revive Dark', desc: 'efeito sombrio', cost: 30000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-solar', name: 'Revive Solar', desc: 'efeito solar', cost: 35000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-lunar', name: 'Revive Lunar', desc: 'efeito lunar', cost: 35000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-galaxy', name: 'Revive Galaxy', desc: 'efeito galáctico', cost: 45000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-star', name: 'Revive Star', desc: 'efeito estelar', cost: 40000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-meteor', name: 'Revive Meteor', desc: 'efeito meteoro', cost: 42500, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-prism', name: 'Revive Prism', desc: 'efeito prisma', cost: 45000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-mystic', name: 'Revive Mystic', desc: 'efeito místico', cost: 50000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-titan', name: 'Revive Titan', desc: 'efeito titã', cost: 55000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-king', name: 'Revive King', desc: 'efeito real', cost: 60000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-champion', name: 'Revive Champion', desc: 'efeito campeão', cost: 65000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-legendary', name: 'Revive Legendary', desc: 'efeito lendário', cost: 75000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-ancient', name: 'Revive Ancient', desc: 'efeito antigo', cost: 80000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-divine', name: 'Revive Divine', desc: 'efeito divino', cost: 100000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-eternal', name: 'Revive Eternal', desc: 'efeito eterno', cost: 125000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-ultimate', name: 'Revive Ultimate', desc: 'efeito supremo', cost: 150000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 1 } },
  { item: 'revive2-revive-5x', name: 'Revive 5x', desc: '5 usos', cost: 50000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 5 } },
  { item: 'revive2-revive-10x', name: 'Revive 10x', desc: '10 usos', cost: 90000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 10 } },
  { item: 'revive2-revive-pack', name: 'Revive Pack', desc: '25 usos', cost: 200000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 25 } },
  { item: 'revive2-revive-master', name: 'Revive Master', desc: 'pacote especial', cost: 250000, currency: 'money', icon: '💖', grant: { type: 'revive', count: 3 } },
  { item: 'revive-infinity', name: 'Revive Infinity', desc: 'usos ilimitados · Desponivel apenas em conquistas', cost: 0, currency: 'money', icon: '♾️', purchasable: false },
    ]
  },
  {
    id: 'rebirth', icon: '🔁', title: 'REBIRTH · EXCLUSIVOS', currency: 'rt',
    items: [
      { item: 'rt-revive-triplo', name: 'Revive Triplo', desc: '3 usos', cost: 1, currency: 'rt', icon: '💖', grant: { type: 'revive', count: 3 } },
      { item: 'rt-ammo-nuclear', name: 'Munição Nuclear', desc: '100 tiros de Hyper Gun', cost: 1, currency: 'rt', icon: '☢️', grant: { type: 'ammo', weapon: 'hyper-gun', amount: 100 } },
      { item: 'rt-golden-gun', name: 'Golden Gun', desc: 'pistola dourada', cost: 2, currency: 'rt', icon: '🟡', grant: { type: 'weapon', id: 'golden-gun' } },
      { item: 'rt-skin-divine', name: 'Divine Skin', desc: 'estilo divino', cost: 2, currency: 'rt', icon: '✨', grant: { type: 'flag', key: 'skin2_divine_skin' } },
      { item: 'rt-wskin-ultimate', name: 'Ultimate Weapon', desc: 'visual lendário da arma', cost: 2, currency: 'rt', icon: '🎨', grant: { type: 'flag', key: 'wskin2_ultimate_weapon' } },
      { item: 'rt-skill-infinity', name: 'Skill Infinity', desc: 'todos os efeitos · CD 90s', cost: 3, currency: 'rt', icon: '♾️', grant: { type: 'flag', key: 'skill_infinity' } },
      { item: 'rt-hyper-gun', name: 'Hyper Gun', desc: 'arma experimental', cost: 4, currency: 'rt', icon: '💥', grant: { type: 'weapon', id: 'hyper-gun' } },
      { item: 'rt-armor-eternal', name: 'Armadura Eternal', desc: '+2500 HP · permanente', cost: 4, currency: 'rt', icon: '♾️', grant: { type: 'armorHp', hp: 2500 } },
      { item: 'rt-armor-ultimate', name: 'Armadura Ultimate', desc: '+3000 HP · permanente', cost: 5, currency: 'rt', icon: '🌟', grant: { type: 'armorHp', hp: 3000 } },
      { item: 'rt-skill-ultimate', name: 'Ultimate', desc: 'habilidade suprema · CD 180s', cost: 6, currency: 'rt', icon: '👑', grant: { type: 'flag', key: 'skill_ultimate' } }
    ]
  }
];

export const SHOP_ITEM_MAP = {};
for (const section of SHOP_SECTIONS) {
  for (const it of section.items) SHOP_ITEM_MAP[it.item] = it;
}
